In [2]:
import pandas as pd

In [3]:
tobin1 = pd.read_csv('1기_시가총액tobinQ증가율까지(t년).csv')
tobin2 = pd.read_csv('2기_시가총액tobinQ증가율까지(t년).csv')
tobin2

,종목명,업종명,회계연도,t년_시가총액,t년_tobinQ,t년대비 t+1년 tobinQ 증가율,t년대비 t+1년 시가총액 증가율
0,AK홀딩스,기타금융,2020,3.330000e+11,0.776140,2.027999,-23.123123
1,BYC,섬유의복,2020,2.090000e+11,0.640889,19.401490,53.588517
2,CJ,기타금융,2020,3.120000e+12,0.693320,-2.556042,-8.653846
3,CJCGV,서비스업,2020,8.850000e+11,1.137004,3.039371,7.457627
4,CJ대한통운,운수창고업,2020,3.780000e+12,0.972572,-10.235364,-24.074074
...,...,...,...,...,...,...,...
2071,화승코퍼레이션,운수장비,2022,7.007175e+10,0.846650,0.832722,45.565076
2072,효성중공업,전기전자,2022,7.270000e+11,0.919911,15.224050,107.702889
2073,효성첨단소재,화학,2022,1.490000e+12,1.236651,8.568999,20.134228
2074,효성티앤씨,화학,2022,1.510000e+12,0.999807,0.286088,4.635762
2075,효성화학,화학,2022,3.170000e+11,1.064769,1.881466,2.839117

In [4]:
e1_grade_sub = pd.read_csv('csv/재무비율/최종/등급차이/환경_1기_등급차이포함.csv', index_col=0).reset_index(drop=True)
s1_grade_sub = pd.read_csv('csv/재무비율/최종/등급차이/사회_1기_등급차이포함.csv', index_col=0).reset_index(drop=True)
g1_grade_sub = pd.read_csv('csv/재무비율/최종/등급차이/지배구조_1기_등급차이포함.csv', index_col=0).reset_index(drop=True)
t1_grade_sub = pd.read_csv('csv/재무비율/최종/등급차이/통합등급_1기_등급차이포함.csv', index_col=0).reset_index(drop=True)
esg2_grade_sub = pd.read_csv('csv/재무비율/최종/등급차이/esg2기_등급차이포함.csv', index_col=0).reset_index(drop=True)

In [5]:
test = pd.merge(esg2_grade_sub, tobin2, on=['종목명','업종명','회계연도'])
test

,종목명,업종명,종목코드,결산월,회계연도,주기,총자산(천원),유동자산(천원),매출채권(천원),재고자산(천원),...,총자본(천원)_회전율,총부채(천원)_회전율,환경_등급차이,사회_등급차이,지배구조_등급차이,통합_등급차이,t년_시가총액,t년_tobinQ,t년대비 t+1년 tobinQ 증가율,t년대비 t+1년 시가총액 증가율
0,AK홀딩스,기타금융,A006840,12,2020,Annual,4.152092e+09,1.185255e+09,243210194,236961655,...,2.074963,0.906745,1.0,0.0,0.0,0.0,3.330000e+11,0.776140,2.027999,-23.123123
1,AK홀딩스,기타금융,A006840,12,2021,Annual,4.548737e+09,1.352749e+09,287334993,375434184,...,2.634570,0.946606,0.0,1.0,-1.0,0.0,2.560000e+11,0.791880,0.051709,-10.937500
2,AK홀딩스,기타금융,A006840,12,2022,Annual,4.985366e+09,1.578818e+09,332397459,357702292,...,2.998300,1.017722,2.0,1.0,1.0,1.0,2.280000e+11,0.792290,0.860840,-0.438596
3,BYC,섬유의복,A001460,12,2020,Annual,6.791349e+08,1.163563e+08,4338337,34704886,...,0.357576,0.714733,0.0,0.0,0.0,0.0,2.090000e+11,0.640889,19.401490,53.588517
4,BYC,섬유의복,A001460,12,2021,Annual,6.844345e+08,1.333390e+08,4923098,30955006,...,0.341307,0.811589,0.0,-2.0,-3.0,-2.0,3.210000e+11,0.765231,-19.421177,-19.314642
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1513,휴스틸,철강금속,A005010,12,2021,Annual,9.519209e+08,4.119306e+08,94258672,236068035,...,0.984204,1.893904,-1.0,-1.0,-1.0,-1.0,1.140000e+11,0.461759,4.490302,150.000000
1514,휴스틸,철강금속,A005010,12,2022,Annual,1.206374e+09,6.405798e+08,153866354,197585910,...,1.133904,3.468866,1.0,1.0,0.0,1.0,2.850000e+11,0.482493,-6.365047,-1.754386
1515,흥아해운,운수창고업,A003280,12,2020,Annual,2.867760e+08,5.909465e+07,1596076,7553389,...,-3.383781,0.284095,0.0,0.0,0.0,0.0,3.011700e+10,1.196672,168.134776,2054.929094
1516,흥아해운,운수창고업,A003280,12,2021,Annual,2.472987e+08,5.526361e+07,3993001,6823665,...,0.793904,0.566119,1.0,1.0,1.0,1.0,6.490000e+11,3.208694,-50.112353,-49.768875
1517,흥아해운,운수창고업,A003280,12,2022,Annual,3.170599e+08,1.050416e+08,8413615,9225089,...,1.314515,0.978569,1.0,1.0,1.0,1.0,3.260000e+11,1.600742,45.025889,84.355828

In [6]:
test.columns

Index(['종목명', '업종명', '종목코드', '결산월', '회계연도', '주기', '총자산(천원)', '유동자산(천원)',
       '매출채권(천원)', '재고자산(천원)', '유형자산(천원)', '부채및자본총계(천원)', '총부채(천원)',
       '유동부채(천원)', '매입채무(천원)', '단기차입금(천원)', '장기차입금(천원)', '총자본(천원)', '매출액(천원)',
       '매출원가(천원)', '영업이익(천원)', '연구개발비(천원)', '광고선전비(천원)', '당기순이익(천원)',
       '영업활동으로인한현금흐름(천원)', '투자활동으로인한현금흐름(천원)', '재무활동으로인한현금흐름(천원)', '자기자본비율(%)',
       '차입금의존도(%)', '부채비율(%)', '차입금비율(%)', '*매출원가율(%)', 'ROE(당기순이익)(%)',
       '영업이익률(%)', 'EBIT(천원)', '매출총이익률(%)', '총자산(천원)_증가율(%)',
       '유동자산(천원)_증가율(%)', '유형자산(천원)_증가율(%)', '부채및자본총계(천원)_증가율(%)',
       '총부채(천원)_증가율(%)', '유동부채(천원)_증가율(%)', '총자본(천원)_증가율(%)', '매출액(천원)_증가율(%)',
       '영업이익(천원)_증가율(%)', '당기순이익(천원)_증가율(%)', '영업활동으로인한현금흐름(천원)_증가율(%)',
       '투자활동으로인한현금흐름(천원)_증가율(%)', '총자산(천원)_회전율', '총자본(천원)_회전율', '총부채(천원)_회전율',
       '환경_등급차이', '사회_등급차이', '지배구조_등급차이', '통합_등급차이', 't년_시가총액', 't년_tobinQ',
       't년대비 t+1년 tobinQ 증가율', 't년대비 t+1년 시가총액 증가율'],
      dtype='object')

In [7]:
def transform_values(x):
    if x < 0:
        return 0
    elif x == 0:
        return 1
    else :
        return 2

In [13]:
test['t년대비 t+1년 tobinQ 증가율'] = test['t년대비 t+1년 tobinQ 증가율'].apply(transform_values)
test['t년대비 t+1년 시가총액 증가율'] = test['t년대비 t+1년 시가총액 증가율'].apply(transform_values)
test['환경_등급차이'] = test['환경_등급차이'].apply(transform_values)
test['사회_등급차이'] = test['사회_등급차이'].apply(transform_values)
test['지배구조_등급차이'] = test['지배구조_등급차이'].apply(transform_values)
test['통합_등급차이'] = test['통합_등급차이'].apply(transform_values)

In [14]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.multivariate.manova import MANOVA

# 데이터 불러오기
# data = pd.read_csv("your_data.csv")

# 독립 변수와 종속 변수 분리
X = test[['환경_등급차이', '사회_등급차이', '지배구조_등급차이', '통합_등급차이']]  # 독립 변수들
y = test[['t년대비 t+1년 tobinQ 증가율', 't년대비 t+1년 시가총액 증가율']]  # 종속 변수들

# MANOVA 모델 생성 및 적합
manova = MANOVA.from_formula(formula='y ~ X', data=test)
result = manova.mv_test()

# MANOVA 결과 출력
print(result)

                   Multivariate linear model
================================================================

----------------------------------------------------------------
       Intercept        Value  Num DF   Den DF   F Value  Pr > F
----------------------------------------------------------------
          Wilks' lambda 0.3407 2.0000 1512.0000 1463.1743 0.0000
         Pillai's trace 0.6593 2.0000 1512.0000 1463.1743 0.0000
 Hotelling-Lawley trace 1.9354 2.0000 1512.0000 1463.1743 0.0000
    Roy's greatest root 1.9354 2.0000 1512.0000 1463.1743 0.0000
----------------------------------------------------------------

----------------------------------------------------------------
             X            Value  Num DF   Den DF  F Value Pr > F
----------------------------------------------------------------
            Wilks' lambda 0.9238 8.0000 3024.0000 15.2770 0.0000
           Pillai's trace 0.0763 8.0000 3026.0000 15.0076 0.0000
   Hotelling-Lawley trace 0.0823 8.0000 2157.6749 15.5504 0.0000
      Roy's greatest root 0.0804 4.0000 1513.0000 30.4068 0.0000
================================================================

In [15]:
X

      환경_등급차이  사회_등급차이  지배구조_등급차이  통합_등급차이
0           2        1          1        1
1           1        2          0        1
2           2        2          2        2
3           1        1          1        1
4           1        0          0        0
...       ...      ...        ...      ...
1513        0        0          0        0
1514        2        2          1        2
1515        1        1          1        1
1516        2        2          2        2
1517        2        2          2        2

[1518 rows x 4 columns]

In [16]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

# ANOVA 모델 생성
model = ols('y ~ X', data=test).fit()

# ANOVA 테이블 출력
anova_table = sm.stats.anova_lm(model, typ=2)
print("ANOVA Table:")
print(anova_table)

ValueError: endog has evaluated to an array with multiple columns that has shape (1518, 2). This occurs when the variable converted to endog is non-numeric (e.g., bool or str).