In [2]:
import pandas as pd

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_45985/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
_e1 = pd.read_csv('csv/esg/esg최종_수치화/환경1기_최종수정.csv', index_col=0)
_e2 = pd.read_csv('csv/esg/esg최종_수치화/환경2기_최종수정.csv', index_col=0)
_s1 = pd.read_csv('csv/esg/esg최종_수치화/사회1기_최종수정.csv', index_col=0)
_s2 = pd.read_csv('csv/esg/esg최종_수치화/사회2기_최종수정.csv', index_col=0)
_g1 = pd.read_csv('csv/esg/esg최종_수치화/지배1기_최종수정.csv', index_col=0)
_g2 = pd.read_csv('csv/esg/esg최종_수치화/지배2기_최종수정.csv', index_col=0)
_t1 = pd.read_csv('csv/esg/esg최종_수치화/통합1기_최종수정.csv', index_col=0)
_t2 = pd.read_csv('csv/esg/esg최종_수치화/통합2기_최종수정.csv', index_col=0)

In [4]:
datalist_1 = [_e1, _s1, _g1, _t1]
datalist_2 = [_e2, _s2, _g2, _t2]

list_1 = pd.read_csv('csv/종목리스트/최종_1기_리스트_금융업제외.csv', index_col=0)
list_2 = pd.read_csv('csv/종목리스트/최종_2기_리스트_금융업제외.csv', index_col=0)

In [34]:
_e1 = pd.merge(list_1, _e1, on=['종목명','업종명'])
_s1 = pd.merge(list_1, _s1, on=['종목명','업종명'])
_g1 = pd.merge(list_1, _g1, on=['종목명','업종명'])
_t1 = pd.merge(list_1, _t1, on=['종목명','업종명'])
_e2 = pd.merge(list_1, _e2, on=['종목명','업종명'])
_s2 = pd.merge(list_1, _s2, on=['종목명','업종명'])
_g2 = pd.merge(list_1, _g2, on=['종목명','업종명'])
_t2 = pd.merge(list_1, _t2, on=['종목명','업종명'])

In [5]:
# for i in datalist_1 : 
#     i = pd.merge(list_1, i, on=['종목명','업종명'])
#     i.reset_index(drop=True, inplace=True)

# for j in datalist_2 : 
#     j = pd.merge(list_2, i, on=['종목명','업종명'])
#     j.reset_index(drop=True, inplace=True)

# _e1

,종목명,2011환경,2012환경,2013환경,2014환경,2015환경,2016환경,2017환경,2018환경,종목코드,시장구분,업종명,시가총액,2012-2011환경차이,2013-2012환경차이,2014-2013환경차이,2015-2014환경차이,2016-2015환경차이,2017-2016환경차이,2018-2017환경차이
0,AK홀딩스,3.0,2.0,2.0,2.0,2.0,3.0,3.0,2.0,6840.0,KOSPI,기타금융,1.959310e+11,-1.0,0.0,0.0,0.0,1.0,0.0,-1.0
1,BYC,3.0,2.0,3.0,2.0,2.0,2.0,3.0,4.0,1460.0,KOSPI,섬유의복,2.464110e+11,-1.0,1.0,-1.0,0.0,0.0,1.0,1.0
2,CJ,4.0,3.0,3.0,3.0,3.0,4.0,5.0,5.0,1040.0,KOSPI,기타금융,3.574180e+12,-1.0,0.0,0.0,0.0,1.0,1.0,0.0
3,CJCGV,3.0,3.0,3.0,2.0,3.0,2.0,4.0,5.0,79160.0,KOSPI,서비스업,7.101060e+11,0.0,0.0,-1.0,1.0,-1.0,2.0,1.0
4,CJ대한통운,3.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,120.0,KOSPI,운수창고업,2.817320e+12,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,풀무원,5.0,5.0,5.0,5.0,4.0,5.0,6.0,6.0,17810.0,KOSPI,음식료품,4.700260e+11,0.0,0.0,0.0,-1.0,1.0,1.0,0.0
556,풍산,4.0,4.0,4.0,4.0,4.0,3.0,4.0,3.0,103140.0,KOSPI,철강금속,1.670250e+12,0.0,0.0,0.0,0.0,-1.0,1.0,-1.0
557,풍산홀딩스,3.0,3.0,3.0,3.0,3.0,3.0,4.0,4.0,5810.0,KOSPI,기타금융,4.188220e+11,0.0,0.0,0.0,0.0,0.0,1.0,0.0
558,KH필룩스,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,33180.0,KOSPI,전기전자,1.205790e+11,0.0,0.0,0.0,0.0,0.0,-1.0,0.0
559,하나금융지주,6.0,6.0,6.0,6.0,6.0,6.0,5.0,6.0,86790.0,KOSPI,기타금융,1.666430e+13,0.0,0.0,0.0,0.0,0.0,-1.0,1.0

# 환경

In [54]:
e1_2011 = _e1[['종목명', '업종명']]
e1_2011['등급차이'] = _e1['2012-2011환경차이']
e1_2011['회계연도'] = 2011

e1_2012 = _e1[['종목명', '업종명']]
e1_2012['등급차이'] = _e1['2013-2012환경차이']
e1_2012['회계연도'] = 2012

e1_2013 = _e1[['종목명', '업종명']]
e1_2013['등급차이'] = _e1['2014-2013환경차이']
e1_2013['회계연도'] = 2013

e1_2014 = _e1[['종목명', '업종명']]
e1_2014['등급차이'] = _e1['2015-2014환경차이']
e1_2014['회계연도'] = 2014

e1_2015 = _e1[['종목명', '업종명']]
e1_2015['등급차이'] = _e1['2016-2015환경차이']
e1_2015['회계연도'] = 2015

e1_2016 = _e1[['종목명', '업종명']]
e1_2016['등급차이'] = _e1['2017-2016환경차이']
e1_2016['회계연도'] = 2016

e1_2017 = _e1[['종목명', '업종명']]
e1_2017['등급차이'] = _e1['2018-2017환경차이']
e1_2017['회계연도'] = 2017

e2_2020 = _e2[['종목명', '업종명']]
e2_2020['등급차이'] = _e2['2021-2020환경차이']
e2_2020['회계연도'] = 2020

e2_2021 = _e2[['종목명', '업종명']]
e2_2021['등급차이'] = _e2['2022-2021환경차이']
e2_2021['회계연도'] = 2021

e2_2022 = _e2[['종목명', '업종명']]
e2_2022['등급차이'] = _e2['2023-2022환경차이']
e2_2022['회계연도'] = 2022

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2011['등급차이'] = _e1['2012-2011환경차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2011['회계연도'] = 2011
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2012['등급차이'] = _e1['2013-2012환경차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2012['회계연도'] = 2012
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2013['등급차이'] = _e1['2014-2013환경차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2013['회계연도'] = 2013
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2014['등급차이'] = _e1['2015-2014환경차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2014['회계연도'] = 2014
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2015['등급차이'] = _e1['2016-2015환경차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2015['회계연도'] = 2015
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2016['등급차이'] = _e1['2017-2016환경차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2016['회계연도'] = 2016
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2017['등급차이'] = _e1['2018-2017환경차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2017['회계연도'] = 2017
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e2_2020['등급차이'] = _e2['2021-2020환경차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e2_2020['회계연도'] = 2020
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e2_2021['등급차이'] = _e2['2022-2021환경차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e2_2021['회계연도'] = 2021
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e2_2022['등급차이'] = _e2['2023-2022환경차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/2260898989.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e2_2022['회계연도'] = 2022

In [89]:
e1_list = [e1_2011, e1_2012, e1_2013, e1_2014, e1_2015, e1_2016, e1_2017]
e2_list = [e2_2020, e2_2021, e2_2022]

e1 = pd.concat(e1_list, axis=0).reset_index(drop=True)
e2 = pd.concat(e2_list, axis=0).reset_index(drop=True)

e1.columns=['종목명', '업종명', '환경_등급차이', '회계연도']
e2.columns=['종목명', '업종명', '환경_등급차이', '회계연도']
e2

         종목명    업종명  환경_등급차이  회계연도
0      AK홀딩스   기타금융      1.0  2020
1        BYC   섬유의복      0.0  2020
2         CJ   기타금융      1.0  2020
3      CJCGV   서비스업      0.0  2020
4     CJ대한통운  운수창고업      0.0  2020
...      ...    ...      ...   ...
1537   효성ITX   서비스업      1.0  2022
1538      후성     화학      2.0  2022
1539     휴니드   전기전자      1.0  2022
1540     휴스틸   철강금속      1.0  2022
1541    흥아해운  운수창고업      1.0  2022

[1542 rows x 4 columns]

# 사회

In [56]:
s1_2011 = _s1[['종목명', '업종명']]
s1_2011['등급차이'] = _s1['2012-2011사회차이']
s1_2011['회계연도'] = 2011

s1_2012 = _s1[['종목명', '업종명']]
s1_2012['등급차이'] = _s1['2013-2012사회차이']
s1_2012['회계연도'] = 2012

s1_2013 = _s1[['종목명', '업종명']]
s1_2013['등급차이'] = _s1['2014-2013사회차이']
s1_2013['회계연도'] = 2013

s1_2014 = _s1[['종목명', '업종명']]
s1_2014['등급차이'] = _s1['2015-2014사회차이']
s1_2014['회계연도'] = 2014

s1_2015 = _s1[['종목명', '업종명']]
s1_2015['등급차이'] = _s1['2016-2015사회차이']
s1_2015['회계연도'] = 2015

s1_2016 = _s1[['종목명', '업종명']]
s1_2016['등급차이'] = _s1['2017-2016사회차이']
s1_2016['회계연도'] = 2016

s1_2017 = _s1[['종목명', '업종명']]
s1_2017['등급차이'] = _s1['2018-2017사회차이']
s1_2017['회계연도'] = 2017

s2_2020 = _s2[['종목명', '업종명']]
s2_2020['등급차이'] = _s2['2021-2020사회차이']
s2_2020['회계연도'] = 2020

s2_2021 = _s2[['종목명', '업종명']]
s2_2021['등급차이'] = _s2['2022-2021사회차이']
s2_2021['회계연도'] = 2021

s2_2022 = _s2[['종목명', '업종명']]
s2_2022['등급차이'] = _s2['2023-2022사회차이']
s2_2022['회계연도'] = 2022

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2011['등급차이'] = _s1['2012-2011사회차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2011['회계연도'] = 2011
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2012['등급차이'] = _s1['2013-2012사회차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2012['회계연도'] = 2012
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2013['등급차이'] = _s1['2014-2013사회차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2013['회계연도'] = 2013
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2014['등급차이'] = _s1['2015-2014사회차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2014['회계연도'] = 2014
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2015['등급차이'] = _s1['2016-2015사회차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2015['회계연도'] = 2015
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2016['등급차이'] = _s1['2017-2016사회차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2016['회계연도'] = 2016
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2017['등급차이'] = _s1['2018-2017사회차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2017['회계연도'] = 2017
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2_2020['등급차이'] = _s2['2021-2020사회차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2_2020['회계연도'] = 2020
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2_2021['등급차이'] = _s2['2022-2021사회차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2_2021['회계연도'] = 2021
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2_2022['등급차이'] = _s2['2023-2022사회차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/4083302235.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2_2022['회계연도'] = 2022

In [90]:
s1_list = [s1_2011, s1_2012, s1_2013, s1_2014, s1_2015, s1_2016, s1_2017]
s2_list = [s2_2020, s2_2021, s2_2022]

s1 = pd.concat(s1_list, axis=0).reset_index(drop=True)
s2 = pd.concat(s2_list, axis=0).reset_index(drop=True)

s1.columns=['종목명', '업종명', '사회_등급차이', '회계연도']
s2.columns=['종목명', '업종명', '사회_등급차이', '회계연도']
s2

         종목명    업종명  사회_등급차이  회계연도
0      AK홀딩스   기타금융      0.0  2020
1        BYC   섬유의복      0.0  2020
2         CJ   기타금융      1.0  2020
3      CJCGV   서비스업      0.0  2020
4     CJ대한통운  운수창고업      3.0  2020
...      ...    ...      ...   ...
1537   효성ITX   서비스업      1.0  2022
1538      후성     화학      1.0  2022
1539     휴니드   전기전자     -1.0  2022
1540     휴스틸   철강금속      1.0  2022
1541    흥아해운  운수창고업      1.0  2022

[1542 rows x 4 columns]

# 지배구조

In [39]:
_g1

,종목명,업종명,2011지배구조,2012지배구조,2013지배구조,2014지배구조,2015지배구조,2016지배구조,2017지배구조,2018지배구조,종목코드,시장구분,시가총액,2012-2011지배구조차이,2013-2012지배구조차이,2014-2013지배구조차이,2015-2014지배구조차이,2016-2015지배구조차이,2017-2016지배구조차이,2018-2017지배구조차이
0,AK홀딩스,기타금융,3.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,6840.0,KOSPI,1.959310e+11,1.0,-1.0,0.0,0.0,0.0,0.0,0.0
1,BYC,섬유의복,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1460.0,KOSPI,2.464110e+11,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,CJ대한통운,운수창고업,3.0,3.0,4.0,4.0,4.0,5.0,5.0,5.0,120.0,KOSPI,2.817320e+12,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,CJ제일제당,음식료품,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,97950.0,KOSPI,5.223800e+12,-1.0,1.0,0.0,0.0,0.0,0.0,0.0
4,DB하이텍,전기전자,4.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,990.0,KOSPI,1.818120e+12,0.0,0.0,-1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,화천기계,기계,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,10660.0,KOSPI,8.096000e+10,0.0,0.0,0.0,0.0,0.0,0.0,0.0
281,효성,기타금융,4.0,4.0,4.0,3.0,4.0,5.0,4.0,4.0,4800.0,KOSPI,1.224230e+12,0.0,0.0,-1.0,1.0,1.0,-1.0,0.0
282,후성,화학,3.0,3.0,3.0,3.0,4.0,4.0,4.0,4.0,93370.0,KOSPI,7.482120e+11,0.0,0.0,0.0,1.0,0.0,0.0,0.0
283,휴니드,전기전자,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,5870.0,KOSPI,1.037530e+11,0.0,0.0,0.0,0.0,0.0,0.0,0.0
284,휴스틸,철강금속,3.0,4.0,3.0,4.0,4.0,4.0,3.0,3.0,5010.0,KOSPI,2.511610e+11,1.0,-1.0,1.0,0.0,0.0,-1.0,0.0

In [58]:
g1_2011 = _g1[['종목명', '업종명']]
g1_2011['등급차이'] = _g1['2012-2011지배구조차이']
g1_2011['회계연도'] = 2011

g1_2012 = _g1[['종목명', '업종명']]
g1_2012['등급차이'] = _g1['2013-2012지배구조차이']
g1_2012['회계연도'] = 2012

g1_2013 = _g1[['종목명', '업종명']]
g1_2013['등급차이'] = _g1['2014-2013지배구조차이']
g1_2013['회계연도'] = 2013

g1_2014 = _g1[['종목명', '업종명']]
g1_2014['등급차이'] = _g1['2015-2014지배구조차이']
g1_2014['회계연도'] = 2014

g1_2015 = _g1[['종목명', '업종명']]
g1_2015['등급차이'] = _g1['2016-2015지배구조차이']
g1_2015['회계연도'] = 2015

g1_2016 = _g1[['종목명', '업종명']]
g1_2016['등급차이'] = _g1['2017-2016지배구조차이']
g1_2016['회계연도'] = 2016

g1_2017 = _g1[['종목명', '업종명']]
g1_2017['등급차이'] = _g1['2018-2017지배구조차이']
g1_2017['회계연도'] = 2017

g2_2020 = _g2[['종목명', '업종명']]
g2_2020['등급차이'] = _g2['2021-2020지배구조차이']
g2_2020['회계연도'] = 2020

g2_2021 = _g2[['종목명', '업종명']]
g2_2021['등급차이'] = _g2['2022-2021지배구조차이']
g2_2021['회계연도'] = 2021

g2_2022 = _g2[['종목명', '업종명']]
g2_2022['등급차이'] = _g2['2023-2022지배구조차이']
g2_2022['회계연도'] = 2022

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2011['등급차이'] = _g1['2012-2011지배구조차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2011['회계연도'] = 2011
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2012['등급차이'] = _g1['2013-2012지배구조차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2012['회계연도'] = 2012
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2013['등급차이'] = _g1['2014-2013지배구조차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2013['회계연도'] = 2013
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2014['등급차이'] = _g1['2015-2014지배구조차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2014['회계연도'] = 2014
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2015['등급차이'] = _g1['2016-2015지배구조차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2015['회계연도'] = 2015
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2016['등급차이'] = _g1['2017-2016지배구조차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2016['회계연도'] = 2016
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2017['등급차이'] = _g1['2018-2017지배구조차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2017['회계연도'] = 2017
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g2_2020['등급차이'] = _g2['2021-2020지배구조차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g2_2020['회계연도'] = 2020
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g2_2021['등급차이'] = _g2['2022-2021지배구조차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g2_2021['회계연도'] = 2021
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g2_2022['등급차이'] = _g2['2023-2022지배구조차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3667022688.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g2_2022['회계연도'] = 2022

In [91]:
g1_list = [g1_2011, g1_2012, g1_2013, g1_2014, g1_2015, g1_2016, g1_2017]
g2_list = [g2_2020, g2_2021, g2_2022]

g1 = pd.concat(g1_list, axis=0).reset_index(drop=True)
g2 = pd.concat(g2_list, axis=0).reset_index(drop=True)

g1.columns=['종목명', '업종명', '지배구조_등급차이', '회계연도']
g2.columns=['종목명', '업종명', '지배구조_등급차이', '회계연도']
g2

         종목명    업종명  지배구조_등급차이  회계연도
0      AK홀딩스   기타금융        0.0  2020
1        BYC   섬유의복        0.0  2020
2         CJ   기타금융        0.0  2020
3      CJCGV   서비스업        0.0  2020
4     CJ대한통운  운수창고업        0.0  2020
...      ...    ...        ...   ...
1537   효성ITX   서비스업       -1.0  2022
1538      후성     화학        0.0  2022
1539     휴니드   전기전자       -1.0  2022
1540     휴스틸   철강금속        0.0  2022
1541    흥아해운  운수창고업        1.0  2022

[1542 rows x 4 columns]

# 통합등급

In [60]:
t1_2011 = _t1[['종목명', '업종명']]
t1_2011['등급차이'] = _t1['2012-2011통합등급차이']
t1_2011['회계연도'] = 2011

t1_2012 = _t1[['종목명', '업종명']]
t1_2012['등급차이'] = _t1['2013-2012통합등급차이']
t1_2012['회계연도'] = 2012

t1_2013 = _t1[['종목명', '업종명']]
t1_2013['등급차이'] = _t1['2014-2013통합등급차이']
t1_2013['회계연도'] = 2013

t1_2014 = _t1[['종목명', '업종명']]
t1_2014['등급차이'] = _t1['2015-2014통합등급차이']
t1_2014['회계연도'] = 2014

t1_2015 = _t1[['종목명', '업종명']]
t1_2015['등급차이'] = _t1['2016-2015통합등급차이']
t1_2015['회계연도'] = 2015

t1_2016 = _t1[['종목명', '업종명']]
t1_2016['등급차이'] = _t1['2017-2016통합등급차이']
t1_2016['회계연도'] = 2016

t1_2017 = _t1[['종목명', '업종명']]
t1_2017['등급차이'] = _t1['2018-2017통합등급차이']
t1_2017['회계연도'] = 2017

t2_2020 = _t2[['종목명', '업종명']]
t2_2020['등급차이'] = _t2['2021-2020통합등급차이']
t2_2020['회계연도'] = 2020

t2_2021 = _t2[['종목명', '업종명']]
t2_2021['등급차이'] = _t2['2022-2021통합등급차이']
t2_2021['회계연도'] = 2021

t2_2022 = _t2[['종목명', '업종명']]
t2_2022['등급차이'] = _t2['2023-2022통합등급차이']
t2_2022['회계연도'] = 2022

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2011['등급차이'] = _t1['2012-2011통합등급차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2011['회계연도'] = 2011
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2012['등급차이'] = _t1['2013-2012통합등급차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2012['회계연도'] = 2012
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2013['등급차이'] = _t1['2014-2013통합등급차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2013['회계연도'] = 2013
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2014['등급차이'] = _t1['2015-2014통합등급차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2014['회계연도'] = 2014
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2015['등급차이'] = _t1['2016-2015통합등급차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2015['회계연도'] = 2015
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2016['등급차이'] = _t1['2017-2016통합등급차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2016['회계연도'] = 2016
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2017['등급차이'] = _t1['2018-2017통합등급차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2017['회계연도'] = 2017
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t2_2020['등급차이'] = _t2['2021-2020통합등급차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t2_2020['회계연도'] = 2020
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t2_2021['등급차이'] = _t2['2022-2021통합등급차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t2_2021['회계연도'] = 2021
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t2_2022['등급차이'] = _t2['2023-2022통합등급차이']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_43382/3294816891.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t2_2022['회계연도'] = 2022

In [93]:
t1_list = [t1_2011, t1_2012, t1_2013, t1_2014, t1_2015, t1_2016, t1_2017]
t2_list = [t2_2020, t2_2021, t2_2022]

t1 = pd.concat(t1_list, axis=0).reset_index(drop=True)
t2 = pd.concat(t2_list, axis=0).reset_index(drop=True)

t1.columns=['종목명', '업종명', '통합_등급차이', '회계연도']
t2.columns=['종목명', '업종명', '통합_등급차이', '회계연도']
t2

         종목명    업종명  통합_등급차이  회계연도
0      AK홀딩스   기타금융      0.0  2020
1        BYC   섬유의복      0.0  2020
2         CJ   기타금융      0.0  2020
3      CJCGV   서비스업      0.0  2020
4     CJ대한통운  운수창고업      0.0  2020
...      ...    ...      ...   ...
1537   효성ITX   서비스업      0.0  2022
1538      후성     화학      1.0  2022
1539     휴니드   전기전자      0.0  2022
1540     휴스틸   철강금속      1.0  2022
1541    흥아해운  운수창고업      1.0  2022

[1542 rows x 4 columns]

In [44]:
t1['종목명'].nunique()

383

In [45]:
s1['업종명'].value_counts()

업종명
화학             420
유통업            231
전기전자           231
서비스업           217
의약품            196
운수장비           189
기계             182
기타금융           182
철강금속           175
음식료품           126
건설업            112
운수창고업          112
섬유의복           105
종이목재            84
비금속광물           56
기타제조업           49
전기가스업           49
통신업             21
의료정밀            21
농업, 임업 및 어업      7
Name: count, dtype: int64

In [62]:
e1

         종목명    업종명  등급차이  회계연도
0      AK홀딩스   기타금융  -1.0  2011
1        BYC   섬유의복  -1.0  2011
2         CJ   기타금융  -1.0  2011
3      CJCGV   서비스업   0.0  2011
4     CJ대한통운  운수창고업   0.0  2011
...      ...    ...   ...   ...
3579   효성ITX   서비스업  -1.0  2017
3580      후성     화학   1.0  2017
3581     휴니드   전기전자   0.0  2017
3582     휴스틸   철강금속   0.0  2017
3583    흥아해운  운수창고업  -1.0  2017

[3584 rows x 4 columns]

## 재무데이터 합치기

In [95]:
total_1 = pd.read_csv('csv/재무비율/정말최종_재무1기.csv', index_col=0)
total_2 = pd.read_csv('csv/재무비율/정말최종_재무2기.csv', index_col=0)

In [96]:
total_1.reset_index(drop=True, inplace=True)
total_2.reset_index(drop=True, inplace=True)

In [97]:
total_1

,종목명,업종명,종목코드,결산월,회계연도,주기,총자산(천원),유동자산(천원),매출채권(천원),재고자산(천원),...,유동부채(천원)_증가율(%),총자본(천원)_증가율(%),매출액(천원)_증가율(%),영업이익(천원)_증가율(%),당기순이익(천원)_증가율(%),영업활동으로인한현금흐름(천원)_증가율(%),투자활동으로인한현금흐름(천원)_증가율(%),총자산(천원)_회전율,총자본(천원)_회전율,총부채(천원)_회전율
0,AK홀딩스,기타금융,A006840,12,2011,Annual,7.973953e+08,368464610.0,164957170,100459041,...,8.714815,31.095649,-70.002310,-73.225758,-22.671420,114.044689,551.323235,0.489446,1.111925,0.874290
1,AK홀딩스,기타금융,A006840,12,2012,Annual,1.062013e+09,455173056.0,243262270,120241742,...,20.044521,45.532722,9.681788,31.058911,340.927530,-63.805247,-96.310584,0.403073,0.838010,0.776615
2,AK홀딩스,기타금융,A006840,12,2013,Annual,2.374994e+09,702558263.0,300681262,141634818,...,202.828756,24.315318,423.508219,302.509703,-44.002663,1049.631550,-422.996213,0.943569,3.528971,1.287935
3,AK홀딩스,기타금융,A006840,12,2014,Annual,2.773154e+09,860690585.0,330216202,229358723,...,-5.803466,30.233802,28.242304,35.402624,-12.942332,20.406794,-1115.904708,1.036320,3.475007,1.476704
4,AK홀딩스,기타금융,A006840,12,2015,Annual,2.495515e+09,969178974.0,224543905,203315762,...,-3.178090,9.018106,-2.321824,-27.929648,-139.708844,-35.720894,-174.076296,1.124877,3.113541,1.761158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4075,흥아해운,운수창고업,A003280,12,2014,Annual,6.492400e+08,153440914.0,34651440,13193030,...,-5.108822,7.760601,7.171915,-3.906495,1.063296,-98.376335,-180.023730,1.270940,4.929099,1.712497
4076,흥아해운,운수창고업,A003280,12,2015,Annual,7.916408e+08,136280257.0,32088632,11488626,...,11.615706,3.389326,2.420227,14.408829,-42.676587,7667.595814,-102.318119,1.067549,4.882897,1.366253
4077,흥아해운,운수창고업,A003280,12,2016,Annual,9.585323e+08,102103828.0,33831395,17967554,...,-1.431823,11.215038,-1.581947,-72.247242,-263.287062,-104.097563,2351.907560,0.867729,4.321045,1.085767
4078,흥아해운,운수창고업,A003280,12,2017,Annual,8.734091e+08,115675013.0,38640814,19976759,...,25.035456,-29.354936,0.562842,-320.484176,260.979542,395.969195,-86.417053,0.957658,6.150983,1.134252
4079,흥아해운,운수창고업,A003280,12,2018,Annual,8.036985e+08,108354984.0,40090490,18807927,...,-3.403044,-46.207750,-87.946250,-13.821467,39.599067,390.337868,-4345.093446,0.125446,1.378310,0.138007

In [98]:
e1_total = pd.merge(total_1, e1, on=['종목명','업종명','회계연도'])
s1_total = pd.merge(total_1, s1, on=['종목명','업종명','회계연도'])
g1_total = pd.merge(total_1, g1, on=['종목명','업종명','회계연도'])
t1_total = pd.merge(total_1, t1, on=['종목명','업종명','회계연도'])

In [103]:
esg2 = pd.concat([e2, s2['사회_등급차이'], g2['지배구조_등급차이'], t2['통합_등급차이']], axis=1)
esg2

         종목명    업종명  환경_등급차이  회계연도  사회_등급차이  지배구조_등급차이  통합_등급차이
0      AK홀딩스   기타금융      1.0  2020      0.0        0.0      0.0
1        BYC   섬유의복      0.0  2020      0.0        0.0      0.0
2         CJ   기타금융      1.0  2020      1.0        0.0      0.0
3      CJCGV   서비스업      0.0  2020      0.0        0.0      0.0
4     CJ대한통운  운수창고업      0.0  2020      3.0        0.0      0.0
...      ...    ...      ...   ...      ...        ...      ...
1537   효성ITX   서비스업      1.0  2022      1.0       -1.0      0.0
1538      후성     화학      2.0  2022      1.0        0.0      1.0
1539     휴니드   전기전자      1.0  2022     -1.0       -1.0      0.0
1540     휴스틸   철강금속      1.0  2022      1.0        0.0      1.0
1541    흥아해운  운수창고업      1.0  2022      1.0        1.0      1.0

[1542 rows x 7 columns]

In [104]:
esg2_total = pd.merge(total_2, esg2, on=['종목명','업종명','회계연도'])

In [105]:
e1_total.to_csv('csv/재무비율/최종/환경_1기_등급차이포함.csv')
s1_total.to_csv('csv/재무비율/최종/사회_1기_등급차이포함.csv')
g1_total.to_csv('csv/재무비율/최종/지배구조_1기_등급차이포함.csv')
t1_total.to_csv('csv/재무비율/최종/통합등급_1기_등급차이포함.csv')

esg2_total.to_csv('csv/재무비율/최종/esg2기_등급차이포함.csv')

In [74]:
t2

         종목명    업종명  등급차이  회계연도
0      AK홀딩스   기타금융   0.0  2020
1        BYC   섬유의복   0.0  2020
2         CJ   기타금융   0.0  2020
3      CJCGV   서비스업   0.0  2020
4     CJ대한통운  운수창고업   0.0  2020
...      ...    ...   ...   ...
1537   효성ITX   서비스업   0.0  2022
1538      후성     화학   1.0  2022
1539     휴니드   전기전자   0.0  2022
1540     휴스틸   철강금속   1.0  2022
1541    흥아해운  운수창고업   1.0  2022

[1542 rows x 4 columns]

## t+1 등급차이

In [14]:
e1_grade_sub = pd.read_csv('csv/재무비율/최종/등급차이/환경_1기_등급차이포함.csv', index_col=0).reset_index(drop=True)
s1_grade_sub = pd.read_csv('csv/재무비율/최종/등급차이/사회_1기_등급차이포함.csv', index_col=0).reset_index(drop=True)
g1_grade_sub = pd.read_csv('csv/재무비율/최종/등급차이/지배구조_1기_등급차이포함.csv', index_col=0).reset_index(drop=True)
t1_grade_sub = pd.read_csv('csv/재무비율/최종/등급차이/통합등급_1기_등급차이포함.csv', index_col=0).reset_index(drop=True)
esg2_grade_sub = pd.read_csv('csv/재무비율/최종/등급차이/esg2기_등급차이포함.csv', index_col=0).reset_index(drop=True)

In [15]:
e1_grade_sub

,종목명,업종명,종목코드,결산월,회계연도,주기,총자산(천원),유동자산(천원),매출채권(천원),재고자산(천원),...,총자본(천원)_증가율(%),매출액(천원)_증가율(%),영업이익(천원)_증가율(%),당기순이익(천원)_증가율(%),영업활동으로인한현금흐름(천원)_증가율(%),투자활동으로인한현금흐름(천원)_증가율(%),총자산(천원)_회전율,총자본(천원)_회전율,총부채(천원)_회전율,환경_등급차이
0,AK홀딩스,기타금융,A006840,12,2011,Annual,7.973953e+08,368464610.0,164957170,100459041,...,31.095649,-70.002310,-73.225758,-22.671420,114.044689,551.323235,0.489446,1.111925,0.874290,-1.0
1,AK홀딩스,기타금융,A006840,12,2012,Annual,1.062013e+09,455173056.0,243262270,120241742,...,45.532722,9.681788,31.058911,340.927530,-63.805247,-96.310584,0.403073,0.838010,0.776615,0.0
2,AK홀딩스,기타금융,A006840,12,2013,Annual,2.374994e+09,702558263.0,300681262,141634818,...,24.315318,423.508219,302.509703,-44.002663,1049.631550,-422.996213,0.943569,3.528971,1.287935,0.0
3,AK홀딩스,기타금융,A006840,12,2014,Annual,2.773154e+09,860690585.0,330216202,229358723,...,30.233802,28.242304,35.402624,-12.942332,20.406794,-1115.904708,1.036320,3.475007,1.476704,0.0
4,AK홀딩스,기타금융,A006840,12,2015,Annual,2.495515e+09,969178974.0,224543905,203315762,...,9.018106,-2.321824,-27.929648,-139.708844,-35.720894,-174.076296,1.124877,3.113541,1.761158,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3551,흥아해운,운수창고업,A003280,12,2013,Annual,5.710601e+08,177757981.0,28756477,14418731,...,24.611435,5.977506,-43.435139,11.031152,-0.255439,-8.265543,1.348241,4.956174,1.852062,0.0
3552,흥아해운,운수창고업,A003280,12,2014,Annual,6.492400e+08,153440914.0,34651440,13193030,...,7.760601,7.171915,-3.906495,1.063296,-98.376335,-180.023730,1.270940,4.929099,1.712497,0.0
3553,흥아해운,운수창고업,A003280,12,2015,Annual,7.916408e+08,136280257.0,32088632,11488626,...,3.389326,2.420227,14.408829,-42.676587,7667.595814,-102.318119,1.067549,4.882897,1.366253,-1.0
3554,흥아해운,운수창고업,A003280,12,2016,Annual,9.585323e+08,102103828.0,33831395,17967554,...,11.215038,-1.581947,-72.247242,-263.287062,-104.097563,2351.907560,0.867729,4.321045,1.085767,1.0
3555,흥아해운,운수창고업,A003280,12,2017,Annual,8.734091e+08,115675013.0,38640814,19976759,...,-29.354936,0.562842,-320.484176,260.979542,395.969195,-86.417053,0.957658,6.150983,1.134252,-1.0

In [16]:
e1_grade_sub['t+1년도_환경_등급차이'] = e1_grade_sub.groupby('종목명')['환경_등급차이'].shift(1)
e1_grade_sub.dropna(inplace=True)
e1_grade_sub.reset_index(drop=True, inplace=True)

s1_grade_sub['t+1년도_환경_등급차이'] = s1_grade_sub.groupby('종목명')['사회_등급차이'].shift(1)
s1_grade_sub.dropna(inplace=True)
s1_grade_sub.reset_index(drop=True, inplace=True)

g1_grade_sub['t+1년도_환경_등급차이'] = g1_grade_sub.groupby('종목명')['지배구조_등급차이'].shift(1)
g1_grade_sub.dropna(inplace=True)
g1_grade_sub.reset_index(drop=True, inplace=True)

t1_grade_sub['t+1년도_환경_등급차이'] = t1_grade_sub.groupby('종목명')['통합_등급차이'].shift(1)
t1_grade_sub.dropna(inplace=True)
t1_grade_sub.reset_index(drop=True, inplace=True)

esg2_grade_sub['t+1년도_환경_등급차이'] = esg2_grade_sub.groupby('종목명')['환경_등급차이'].shift(1)
esg2_grade_sub['t+1년도_사회_등급차이'] = esg2_grade_sub.groupby('종목명')['사회_등급차이'].shift(1)
esg2_grade_sub['t+1년도_지배구조_등급차이'] = esg2_grade_sub.groupby('종목명')['지배구조_등급차이'].shift(1)
esg2_grade_sub['t+1년도_통합_등급차이'] = esg2_grade_sub.groupby('종목명')['통합_등급차이'].shift(1)
esg2_grade_sub.dropna(inplace=True)
esg2_grade_sub.reset_index(drop=True, inplace=True)
esg2_grade_sub

,종목명,업종명,종목코드,결산월,회계연도,주기,총자산(천원),유동자산(천원),매출채권(천원),재고자산(천원),...,총자본(천원)_회전율,총부채(천원)_회전율,환경_등급차이,사회_등급차이,지배구조_등급차이,통합_등급차이,t+1년도_환경_등급차이,t+1년도_사회_등급차이,t+1년도_지배구조_등급차이,t+1년도_통합_등급차이
0,AK홀딩스,기타금융,A006840,12,2021,Annual,4.548737e+09,1.352749e+09,287334993,375434184,...,2.634570,0.946606,0.0,1.0,-1.0,0.0,1.0,0.0,0.0,0.0
1,AK홀딩스,기타금융,A006840,12,2022,Annual,4.985366e+09,1.578818e+09,332397459,357702292,...,2.998300,1.017722,2.0,1.0,1.0,1.0,0.0,1.0,-1.0,0.0
2,BYC,섬유의복,A001460,12,2021,Annual,6.844345e+08,1.333390e+08,4923098,30955006,...,0.341307,0.811589,0.0,-2.0,-3.0,-2.0,0.0,0.0,0.0,0.0
3,BYC,섬유의복,A001460,12,2022,Annual,6.688720e+08,1.201821e+08,4897177,38420150,...,0.329005,1.108046,0.0,0.0,0.0,0.0,0.0,-2.0,-3.0,-2.0
4,CJ,기타금융,A001040,12,2021,Annual,4.195600e+10,1.205239e+10,3640572265,2735868912,...,2.094571,1.352714,0.0,-1.0,-1.0,-1.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,휴니드,전기전자,A005870,12,2022,Annual,3.041254e+08,2.290908e+08,8232215,89891553,...,1.541332,1.392283,1.0,-1.0,-1.0,0.0,-1.0,-2.0,-2.0,-2.0
1008,휴스틸,철강금속,A005010,12,2021,Annual,9.519209e+08,4.119306e+08,94258672,236068035,...,0.984204,1.893904,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,0.0
1009,휴스틸,철강금속,A005010,12,2022,Annual,1.206374e+09,6.405798e+08,153866354,197585910,...,1.133904,3.468866,1.0,1.0,0.0,1.0,-1.0,-1.0,-1.0,-1.0
1010,흥아해운,운수창고업,A003280,12,2021,Annual,2.472987e+08,5.526361e+07,3993001,6823665,...,0.793904,0.566119,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
1011,흥아해운,운수창고업,A003280,12,2022,Annual,3.170599e+08,1.050416e+08,8413615,9225089,...,1.314515,0.978569,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [17]:
e1_grade_sub

,종목명,업종명,종목코드,결산월,회계연도,주기,총자산(천원),유동자산(천원),매출채권(천원),재고자산(천원),...,매출액(천원)_증가율(%),영업이익(천원)_증가율(%),당기순이익(천원)_증가율(%),영업활동으로인한현금흐름(천원)_증가율(%),투자활동으로인한현금흐름(천원)_증가율(%),총자산(천원)_회전율,총자본(천원)_회전율,총부채(천원)_회전율,환경_등급차이,t+1년도_환경_등급차이
0,AK홀딩스,기타금융,A006840,12,2012,Annual,1.062013e+09,4.551731e+08,243262270,120241742,...,9.681788,31.058911,340.927530,-63.805247,-96.310584,0.403073,0.838010,0.776615,0.0,-1.0
1,AK홀딩스,기타금융,A006840,12,2013,Annual,2.374994e+09,7.025583e+08,300681262,141634818,...,423.508219,302.509703,-44.002663,1049.631550,-422.996213,0.943569,3.528971,1.287935,0.0,0.0
2,AK홀딩스,기타금융,A006840,12,2014,Annual,2.773154e+09,8.606906e+08,330216202,229358723,...,28.242304,35.402624,-12.942332,20.406794,-1115.904708,1.036320,3.475007,1.476704,0.0,0.0
3,AK홀딩스,기타금융,A006840,12,2015,Annual,2.495515e+09,9.691790e+08,224543905,203315762,...,-2.321824,-27.929648,-139.708844,-35.720894,-174.076296,1.124877,3.113541,1.761158,1.0,0.0
4,AK홀딩스,기타금융,A006840,12,2016,Annual,2.741947e+09,1.179858e+09,266392319,197859303,...,4.085399,100.975753,-456.066876,125.354273,-189.659189,1.065605,2.888838,1.688407,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3043,흥아해운,운수창고업,A003280,12,2013,Annual,5.710601e+08,1.777580e+08,28756477,14418731,...,5.977506,-43.435139,11.031152,-0.255439,-8.265543,1.348241,4.956174,1.852062,0.0,0.0
3044,흥아해운,운수창고업,A003280,12,2014,Annual,6.492400e+08,1.534409e+08,34651440,13193030,...,7.171915,-3.906495,1.063296,-98.376335,-180.023730,1.270940,4.929099,1.712497,0.0,0.0
3045,흥아해운,운수창고업,A003280,12,2015,Annual,7.916408e+08,1.362803e+08,32088632,11488626,...,2.420227,14.408829,-42.676587,7667.595814,-102.318119,1.067549,4.882897,1.366253,-1.0,0.0
3046,흥아해운,운수창고업,A003280,12,2016,Annual,9.585323e+08,1.021038e+08,33831395,17967554,...,-1.581947,-72.247242,-263.287062,-104.097563,2351.907560,0.867729,4.321045,1.085767,1.0,-1.0
3047,흥아해운,운수창고업,A003280,12,2017,Annual,8.734091e+08,1.156750e+08,38640814,19976759,...,0.562842,-320.484176,260.979542,395.969195,-86.417053,0.957658,6.150983,1.134252,-1.0,1.0

In [18]:
e1_grade_sub.to_csv('csv/재무비율/최종/등급차이/환경_1기_등급차이(t+1).csv', encoding='utf-8-sig')
s1_grade_sub.to_csv('csv/재무비율/최종/등급차이/사회_1기_등급차이(t+1).csv', encoding='utf-8-sig')
g1_grade_sub.to_csv('csv/재무비율/최종/등급차이/지배구조_1기_등급차이(t+1).csv', encoding='utf-8-sig')
t1_grade_sub.to_csv('csv/재무비율/최종/등급차이/통합_1기_등급차이(t+1).csv', encoding='utf-8-sig')
esg2_grade_sub.to_csv('csv/재무비율/최종/등급차이/esg2기_등급차이(t+1).csv', encoding='utf-8-sig')