In [2]:
import pandas as pd

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
_e1 = pd.read_csv('csv/esg/esg최종_수치화/환경1기_최종수정.csv', index_col=0)
_e2 = pd.read_csv('csv/esg/esg최종_수치화/환경2기_최종수정.csv', index_col=0)
_s1 = pd.read_csv('csv/esg/esg최종_수치화/사회1기_최종수정.csv', index_col=0)
_s2 = pd.read_csv('csv/esg/esg최종_수치화/사회2기_최종수정.csv', index_col=0)
_g1 = pd.read_csv('csv/esg/esg최종_수치화/지배1기_최종수정.csv', index_col=0)
_g2 = pd.read_csv('csv/esg/esg최종_수치화/지배2기_최종수정.csv', index_col=0)
_t1 = pd.read_csv('csv/esg/esg최종_수치화/통합1기_최종수정.csv', index_col=0)
_t2 = pd.read_csv('csv/esg/esg최종_수치화/통합2기_최종수정.csv', index_col=0)

In [4]:
list_1 = pd.read_csv('csv/종목리스트/최종_1기_리스트_금융업제외.csv', index_col=0)
list_2 = pd.read_csv('csv/종목리스트/최종_2기_리스트_금융업제외.csv', index_col=0)

In [5]:
_e1 = pd.merge(list_1, _e1, on=['종목명','업종명'])
_s1 = pd.merge(list_1, _s1, on=['종목명','업종명'])
_g1 = pd.merge(list_1, _g1, on=['종목명','업종명'])
_t1 = pd.merge(list_1, _t1, on=['종목명','업종명'])
_e2 = pd.merge(list_1, _e2, on=['종목명','업종명'])
_s2 = pd.merge(list_1, _s2, on=['종목명','업종명'])
_g2 = pd.merge(list_1, _g2, on=['종목명','업종명'])
_t2 = pd.merge(list_1, _t2, on=['종목명','업종명'])

## 환경

In [6]:
e1_2011 = _e1[['종목명', '업종명']]
e1_2011['등급'] = _e1['2011환경']
e1_2011['회계연도'] = 2011

e1_2012 = _e1[['종목명', '업종명']]
e1_2012['등급'] = _e1['2012환경']
e1_2012['회계연도'] = 2012

e1_2013 = _e1[['종목명', '업종명']]
e1_2013['등급'] = _e1['2013환경']
e1_2013['회계연도'] = 2013

e1_2014 = _e1[['종목명', '업종명']]
e1_2014['등급'] = _e1['2014환경']
e1_2014['회계연도'] = 2014

e1_2015 = _e1[['종목명', '업종명']]
e1_2015['등급'] = _e1['2015환경']
e1_2015['회계연도'] = 2015

e1_2016 = _e1[['종목명', '업종명']]
e1_2016['등급'] = _e1['2016환경']
e1_2016['회계연도'] = 2016

e1_2017 = _e1[['종목명', '업종명']]
e1_2017['등급'] = _e1['2017환경']
e1_2017['회계연도'] = 2017

e1_2018 = _e1[['종목명', '업종명']]
e1_2018['등급'] = _e1['2018환경']
e1_2018['회계연도'] = 2018

e2_2020 = _e2[['종목명', '업종명']]
e2_2020['등급'] = _e2['2020환경']
e2_2020['회계연도'] = 2020

e2_2021 = _e2[['종목명', '업종명']]
e2_2021['등급'] = _e2['2021환경']
e2_2021['회계연도'] = 2021

e2_2022 = _e2[['종목명', '업종명']]
e2_2022['등급'] = _e2['2022환경']
e2_2022['회계연도'] = 2022

e2_2023 = _e2[['종목명', '업종명']]
e2_2023['등급'] = _e2['2023환경']
e2_2023['회계연도'] = 2023

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2011['등급'] = _e1['2011환경']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2011['회계연도'] = 2011
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2012['등급'] = _e1['2012환경']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2012['회계연도'] = 2012
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2013['등급'] = _e1['2013환경']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2013['회계연도'] = 2013
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2014['등급'] = _e1['2014환경']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2014['회계연도'] = 2014
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2015['등급'] = _e1['2015환경']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2015['회계연도'] = 2015
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2016['등급'] = _e1['2016환경']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2016['회계연도'] = 2016
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2017['등급'] = _e1['2017환경']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2017['회계연도'] = 2017
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2018['등급'] = _e1['2018환경']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1_2018['회계연도'] = 2018
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e2_2020['등급'] = _e2['2020환경']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e2_2020['회계연도'] = 2020
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e2_2021['등급'] = _e2['2021환경']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e2_2021['회계연도'] = 2021
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e2_2022['등급'] = _e2['2022환경']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e2_2022['회계연도'] = 2022
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e2_2023['등급'] = _e2['2023환경']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/2201120062.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e2_2023['회계연도'] = 2023

In [7]:
e1_list = [e1_2011, e1_2012, e1_2013, e1_2014, e1_2015, e1_2016, e1_2017, e1_2018]
e2_list = [e2_2020, e2_2021, e2_2022, e2_2023]

e1 = pd.concat(e1_list, axis=0).reset_index(drop=True)
e2 = pd.concat(e2_list, axis=0).reset_index(drop=True)

e1.columns=['종목명', '업종명', '환경_등급', '회계연도']
e2.columns=['종목명', '업종명', '환경_등급', '회계연도']
e2

         종목명    업종명  환경_등급  회계연도
0      AK홀딩스   기타금융    2.0  2020
1        BYC   섬유의복    1.0  2020
2         CJ   기타금융    3.0  2020
3      CJCGV   서비스업    3.0  2020
4     CJ대한통운  운수창고업    5.0  2020
...      ...    ...    ...   ...
2051   효성ITX   서비스업    4.0  2023
2052      후성     화학    5.0  2023
2053     휴니드   전기전자    2.0  2023
2054     휴스틸   철강금속    2.0  2023
2055    흥아해운  운수창고업    3.0  2023

[2056 rows x 4 columns]

## 사회

In [8]:
s1_2011 = _s1[['종목명', '업종명']]
s1_2011['등급'] = _s1['2011사회']
s1_2011['회계연도'] = 2011

s1_2012 = _s1[['종목명', '업종명']]
s1_2012['등급'] = _s1['2012사회']
s1_2012['회계연도'] = 2012

s1_2013 = _s1[['종목명', '업종명']]
s1_2013['등급'] = _s1['2013사회']
s1_2013['회계연도'] = 2013

s1_2014 = _s1[['종목명', '업종명']]
s1_2014['등급'] = _s1['2014사회']
s1_2014['회계연도'] = 2014

s1_2015 = _s1[['종목명', '업종명']]
s1_2015['등급'] = _s1['2015사회']
s1_2015['회계연도'] = 2015

s1_2016 = _s1[['종목명', '업종명']]
s1_2016['등급'] = _s1['2016사회']
s1_2016['회계연도'] = 2016

s1_2017 = _s1[['종목명', '업종명']]
s1_2017['등급'] = _s1['2017사회']
s1_2017['회계연도'] = 2017

s1_2018 = _s1[['종목명', '업종명']]
s1_2018['등급'] = _s1['2018사회']
s1_2018['회계연도'] = 2018

s2_2020 = _s2[['종목명', '업종명']]
s2_2020['등급'] = _s2['2020사회']
s2_2020['회계연도'] = 2020

s2_2021 = _s2[['종목명', '업종명']]
s2_2021['등급'] = _s2['2021사회']
s2_2021['회계연도'] = 2021

s2_2022 = _s2[['종목명', '업종명']]
s2_2022['등급'] = _s2['2022사회']
s2_2022['회계연도'] = 2022

s2_2023 = _s2[['종목명', '업종명']]
s2_2023['등급'] = _s2['2023사회']
s2_2023['회계연도'] = 2023

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2011['등급'] = _s1['2011사회']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2011['회계연도'] = 2011
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2012['등급'] = _s1['2012사회']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2012['회계연도'] = 2012
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2013['등급'] = _s1['2013사회']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2013['회계연도'] = 2013
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2014['등급'] = _s1['2014사회']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2014['회계연도'] = 2014
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2015['등급'] = _s1['2015사회']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2015['회계연도'] = 2015
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2016['등급'] = _s1['2016사회']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2016['회계연도'] = 2016
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2017['등급'] = _s1['2017사회']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2017['회계연도'] = 2017
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2018['등급'] = _s1['2018사회']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s1_2018['회계연도'] = 2018
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2_2020['등급'] = _s2['2020사회']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2_2020['회계연도'] = 2020
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2_2021['등급'] = _s2['2021사회']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2_2021['회계연도'] = 2021
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2_2022['등급'] = _s2['2022사회']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2_2022['회계연도'] = 2022
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2_2023['등급'] = _s2['2023사회']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/653958510.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2_2023['회계연도'] = 2023

In [9]:
s1_list = [s1_2011, s1_2012, s1_2013, s1_2014, s1_2015, s1_2016, s1_2017, s1_2018]
s2_list = [s2_2020, s2_2021, s2_2022, s2_2023]

s1 = pd.concat(s1_list, axis=0).reset_index(drop=True)
s2 = pd.concat(s2_list, axis=0).reset_index(drop=True)

s1.columns=['종목명', '업종명', '사회_등급', '회계연도']
s2.columns=['종목명', '업종명', '사회_등급', '회계연도']

## 지배구조

In [10]:
g1_2011 = _g1[['종목명', '업종명']]
g1_2011['등급'] = _g1['2011지배구조']
g1_2011['회계연도'] = 2011

g1_2012 = _g1[['종목명', '업종명']]
g1_2012['등급'] = _g1['2012지배구조']
g1_2012['회계연도'] = 2012

g1_2013 = _g1[['종목명', '업종명']]
g1_2013['등급'] = _g1['2013지배구조']
g1_2013['회계연도'] = 2013

g1_2014 = _g1[['종목명', '업종명']]
g1_2014['등급'] = _g1['2014지배구조']
g1_2014['회계연도'] = 2014

g1_2015 = _g1[['종목명', '업종명']]
g1_2015['등급'] = _g1['2015지배구조']
g1_2015['회계연도'] = 2015

g1_2016 = _g1[['종목명', '업종명']]
g1_2016['등급'] = _g1['2016지배구조']
g1_2016['회계연도'] = 2016

g1_2017 = _g1[['종목명', '업종명']]
g1_2017['등급'] = _g1['2017지배구조']
g1_2017['회계연도'] = 2017

g1_2018 = _g1[['종목명', '업종명']]
g1_2018['등급'] = _g1['2018지배구조']
g1_2018['회계연도'] = 2018

g2_2020 = _g2[['종목명', '업종명']]
g2_2020['등급'] = _g2['2020지배구조']
g2_2020['회계연도'] = 2020

g2_2021 = _g2[['종목명', '업종명']]
g2_2021['등급'] = _g2['2021지배구조']
g2_2021['회계연도'] = 2021

g2_2022 = _g2[['종목명', '업종명']]
g2_2022['등급'] = _g2['2022지배구조']
g2_2022['회계연도'] = 2022

g2_2023 = _g2[['종목명', '업종명']]
g2_2023['등급'] = _g2['2023지배구조']
g2_2023['회계연도'] = 2023

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2011['등급'] = _g1['2011지배구조']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2011['회계연도'] = 2011
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2012['등급'] = _g1['2012지배구조']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2012['회계연도'] = 2012
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2013['등급'] = _g1['2013지배구조']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2013['회계연도'] = 2013
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2014['등급'] = _g1['2014지배구조']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2014['회계연도'] = 2014
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2015['등급'] = _g1['2015지배구조']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2015['회계연도'] = 2015
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2016['등급'] = _g1['2016지배구조']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2016['회계연도'] = 2016
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2017['등급'] = _g1['2017지배구조']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2017['회계연도'] = 2017
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2018['등급'] = _g1['2018지배구조']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g1_2018['회계연도'] = 2018
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g2_2020['등급'] = _g2['2020지배구조']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g2_2020['회계연도'] = 2020
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g2_2021['등급'] = _g2['2021지배구조']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g2_2021['회계연도'] = 2021
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g2_2022['등급'] = _g2['2022지배구조']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g2_2022['회계연도'] = 2022
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g2_2023['등급'] = _g2['2023지배구조']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/1438119816.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g2_2023['회계연도'] = 2023

In [11]:
g1_list = [g1_2011, g1_2012, g1_2013, g1_2014, g1_2015, g1_2016, g1_2017, g1_2018]
g2_list = [g2_2020, g2_2021, g2_2022, g2_2023]

g1 = pd.concat(g1_list, axis=0).reset_index(drop=True)
g2 = pd.concat(g2_list, axis=0).reset_index(drop=True)

g1.columns=['종목명', '업종명', '지배구조_등급', '회계연도']
g2.columns=['종목명', '업종명', '지배구조_등급', '회계연도']
g2

         종목명    업종명  지배구조_등급  회계연도
0      AK홀딩스   기타금융      4.0  2020
1        BYC   섬유의복      4.0  2020
2         CJ   기타금융      5.0  2020
3      CJCGV   서비스업      5.0  2020
4     CJ대한통운  운수창고업      5.0  2020
...      ...    ...      ...   ...
2051   효성ITX   서비스업      3.0  2023
2052      후성     화학      3.0  2023
2053     휴니드   전기전자      1.0  2023
2054     휴스틸   철강금속      2.0  2023
2055    흥아해운  운수창고업      3.0  2023

[2056 rows x 4 columns]

## 통합

In [12]:
t1_2011 = _t1[['종목명', '업종명']]
t1_2011['등급'] = _t1['2011통합등급']
t1_2011['회계연도'] = 2011

t1_2012 = _t1[['종목명', '업종명']]
t1_2012['등급'] = _t1['2012통합등급']
t1_2012['회계연도'] = 2012

t1_2013 = _t1[['종목명', '업종명']]
t1_2013['등급'] = _t1['2013통합등급']
t1_2013['회계연도'] = 2013

t1_2014 = _t1[['종목명', '업종명']]
t1_2014['등급'] = _t1['2014통합등급']
t1_2014['회계연도'] = 2014

t1_2015 = _t1[['종목명', '업종명']]
t1_2015['등급'] = _t1['2015통합등급']
t1_2015['회계연도'] = 2015

t1_2016 = _t1[['종목명', '업종명']]
t1_2016['등급'] = _t1['2016통합등급']
t1_2016['회계연도'] = 2016

t1_2017 = _t1[['종목명', '업종명']]
t1_2017['등급'] = _t1['2017통합등급']
t1_2017['회계연도'] = 2017

t1_2018 = _t1[['종목명', '업종명']]
t1_2018['등급'] = _t1['2018통합등급']
t1_2018['회계연도'] = 2018

t2_2020 = _t2[['종목명', '업종명']]
t2_2020['등급'] = _t2['2020통합등급']
t2_2020['회계연도'] = 2020

t2_2021 = _t2[['종목명', '업종명']]
t2_2021['등급'] = _t2['2021통합등급']
t2_2021['회계연도'] = 2021

t2_2022 = _t2[['종목명', '업종명']]
t2_2022['등급'] = _t2['2022통합등급']
t2_2022['회계연도'] = 2022

t2_2023 = _t2[['종목명', '업종명']]
t2_2023['등급'] = _t2['2023통합등급']
t2_2023['회계연도'] = 2023

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2011['등급'] = _t1['2011통합등급']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2011['회계연도'] = 2011
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2012['등급'] = _t1['2012통합등급']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2012['회계연도'] = 2012
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2013['등급'] = _t1['2013통합등급']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2013['회계연도'] = 2013
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2014['등급'] = _t1['2014통합등급']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2014['회계연도'] = 2014
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2015['등급'] = _t1['2015통합등급']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2015['회계연도'] = 2015
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2016['등급'] = _t1['2016통합등급']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2016['회계연도'] = 2016
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2017['등급'] = _t1['2017통합등급']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2017['회계연도'] = 2017
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2018['등급'] = _t1['2018통합등급']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1_2018['회계연도'] = 2018
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t2_2020['등급'] = _t2['2020통합등급']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t2_2020['회계연도'] = 2020
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t2_2021['등급'] = _t2['2021통합등급']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t2_2021['회계연도'] = 2021
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t2_2022['등급'] = _t2['2022통합등급']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t2_2022['회계연도'] = 2022
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t2_2023['등급'] = _t2['2023통합등급']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_46283/3342038303.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t2_2023['회계연도'] = 2023

In [13]:
t1_list = [t1_2011, t1_2012, t1_2013, t1_2014, t1_2015, t1_2016, t1_2017, t1_2018]
t2_list = [t2_2020, t2_2021, t2_2022, t2_2023]

t1 = pd.concat(t1_list, axis=0).reset_index(drop=True)
t2 = pd.concat(t2_list, axis=0).reset_index(drop=True)

t1.columns=['종목명', '업종명', '통합_등급', '회계연도']
t2.columns=['종목명', '업종명', '통합_등급', '회계연도']
t2

         종목명    업종명  통합_등급  회계연도
0      AK홀딩스   기타금융    4.0  2020
1        BYC   섬유의복    3.0  2020
2         CJ   기타금융    5.0  2020
3      CJCGV   서비스업    5.0  2020
4     CJ대한통운  운수창고업    5.0  2020
...      ...    ...    ...   ...
2051   효성ITX   서비스업    4.0  2023
2052      후성     화학    4.0  2023
2053     휴니드   전기전자    1.0  2023
2054     휴스틸   철강금속    2.0  2023
2055    흥아해운  운수창고업    3.0  2023

[2056 rows x 4 columns]

In [14]:
total_1 = pd.read_csv('csv/재무비율/정말최종_재무1기.csv', index_col=0)
total_2 = pd.read_csv('csv/재무비율/정말최종_재무2기.csv', index_col=0)

In [15]:
total_1.reset_index(drop=True, inplace=True)
total_2.reset_index(drop=True, inplace=True)

In [16]:
e1_total = pd.merge(total_1, e1, on=['종목명','업종명','회계연도'])
s1_total = pd.merge(total_1, s1, on=['종목명','업종명','회계연도'])
g1_total = pd.merge(total_1, g1, on=['종목명','업종명','회계연도'])
t1_total = pd.merge(total_1, t1, on=['종목명','업종명','회계연도'])

In [17]:
esg2 = pd.concat([e2, s2['사회_등급'], g2['지배구조_등급'], t2['통합_등급']], axis=1)
esg2

         종목명    업종명  환경_등급  회계연도  사회_등급  지배구조_등급  통합_등급
0      AK홀딩스   기타금융    2.0  2020    4.0      4.0    4.0
1        BYC   섬유의복    1.0  2020    3.0      4.0    3.0
2         CJ   기타금융    3.0  2020    5.0      5.0    5.0
3      CJCGV   서비스업    3.0  2020    5.0      5.0    5.0
4     CJ대한통운  운수창고업    5.0  2020    3.0      5.0    5.0
...      ...    ...    ...   ...    ...      ...    ...
2051   효성ITX   서비스업    4.0  2023    6.0      3.0    4.0
2052      후성     화학    5.0  2023    5.0      3.0    4.0
2053     휴니드   전기전자    2.0  2023    1.0      1.0    1.0
2054     휴스틸   철강금속    2.0  2023    2.0      2.0    2.0
2055    흥아해운  운수창고업    3.0  2023    4.0      3.0    3.0

[2056 rows x 7 columns]

In [18]:
esg2_total = pd.merge(total_2, esg2, on=['종목명','업종명','회계연도'])

In [79]:
e1_total.to_csv('csv/재무비율/최종/등급/환경_1기_등급.csv')
s1_total.to_csv('csv/재무비율/최종/등급/사회_1기_등급.csv')
g1_total.to_csv('csv/재무비율/최종/등급/지배구조_1기_등급.csv')
t1_total.to_csv('csv/재무비율/최종/등급/통합등급_1기_등급.csv')

esg2_total.to_csv('csv/재무비율/최종/등급/esg2기_등급.csv')

In [94]:
s1_total

,종목명,업종명,종목코드,결산월,회계연도,주기,총자산(천원),유동자산(천원),매출채권(천원),재고자산(천원),...,총자본(천원)_증가율(%),매출액(천원)_증가율(%),영업이익(천원)_증가율(%),당기순이익(천원)_증가율(%),영업활동으로인한현금흐름(천원)_증가율(%),투자활동으로인한현금흐름(천원)_증가율(%),총자산(천원)_회전율,총자본(천원)_회전율,총부채(천원)_회전율,사회_등급
0,AK홀딩스,기타금융,A006840,12,2011,Annual,7.973953e+08,368464610.0,164957170,100459041,...,31.095649,-70.002310,-73.225758,-22.671420,114.044689,551.323235,0.489446,1.111925,0.874290,3.0
1,AK홀딩스,기타금융,A006840,12,2012,Annual,1.062013e+09,455173056.0,243262270,120241742,...,45.532722,9.681788,31.058911,340.927530,-63.805247,-96.310584,0.403073,0.838010,0.776615,3.0
2,AK홀딩스,기타금융,A006840,12,2013,Annual,2.374994e+09,702558263.0,300681262,141634818,...,24.315318,423.508219,302.509703,-44.002663,1049.631550,-422.996213,0.943569,3.528971,1.287935,3.0
3,AK홀딩스,기타금융,A006840,12,2014,Annual,2.773154e+09,860690585.0,330216202,229358723,...,30.233802,28.242304,35.402624,-12.942332,20.406794,-1115.904708,1.036320,3.475007,1.476704,3.0
4,AK홀딩스,기타금융,A006840,12,2015,Annual,2.495515e+09,969178974.0,224543905,203315762,...,9.018106,-2.321824,-27.929648,-139.708844,-35.720894,-174.076296,1.124877,3.113541,1.761158,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3123,흥아해운,운수창고업,A003280,12,2014,Annual,6.492400e+08,153440914.0,34651440,13193030,...,7.760601,7.171915,-3.906495,1.063296,-98.376335,-180.023730,1.270940,4.929099,1.712497,3.0
3124,흥아해운,운수창고업,A003280,12,2015,Annual,7.916408e+08,136280257.0,32088632,11488626,...,3.389326,2.420227,14.408829,-42.676587,7667.595814,-102.318119,1.067549,4.882897,1.366253,3.0
3125,흥아해운,운수창고업,A003280,12,2016,Annual,9.585323e+08,102103828.0,33831395,17967554,...,11.215038,-1.581947,-72.247242,-263.287062,-104.097563,2351.907560,0.867729,4.321045,1.085767,3.0
3126,흥아해운,운수창고업,A003280,12,2017,Annual,8.734091e+08,115675013.0,38640814,19976759,...,-29.354936,0.562842,-320.484176,260.979542,395.969195,-86.417053,0.957658,6.150983,1.134252,3.0
3127,흥아해운,운수창고업,A003280,12,2018,Annual,8.036985e+08,108354984.0,40090490,18807927,...,-46.207750,-87.946250,-13.821467,39.599067,390.337868,-4345.093446,0.125446,1.378310,0.138007,3.0

## t+1 년도 esg 등급 데이터프레임

In [106]:
e1_shift = e1_total.copy()
e1_shift['t+1년도_환경등급'] = e1_total.groupby(['종목명','업종명','종목코드'])['환경_등급'].shift(-1)
e1_shift.dropna(inplace=True)
e1_shift.reset_index(drop=True, inplace=True)

s1_shift = s1_total.copy()
s1_shift['t+1년도_사회등급'] = s1_total.groupby(['종목명','업종명','종목코드'])['사회_등급'].shift(-1)
s1_shift.dropna(inplace=True)
s1_shift.reset_index(drop=True, inplace=True)

g1_shift = g1_total.copy()
g1_shift['t+1년도_지배구조등급'] = g1_total.groupby(['종목명','업종명','종목코드'])['지배구조_등급'].shift(-1)
g1_shift.dropna(inplace=True)
g1_shift.reset_index(drop=True, inplace=True)

t1_shift = t1_total.copy()
t1_shift['t+1년도_통합등급'] = t1_total.groupby(['종목명','업종명','종목코드'])['통합_등급'].shift(-1)
t1_shift.dropna(inplace=True)
t1_shift.reset_index(drop=True, inplace=True)

esg2_shift = esg2_total.copy()
esg2_shift[['t+1년도_환경등급','t+1년도_사회등급','t+1년도_지배구조등급','t+1년도_통합등급']] = esg2_total.groupby(['종목명','업종명','종목코드'])[['환경_등급','사회_등급','지배구조_등급','통합_등급']].shift(-1)
esg2_shift.dropna(inplace=True)
esg2_shift.reset_index(drop=True, inplace=True)

In [107]:
e1_shift.to_csv('csv/재무비율/최종/등급/환경_1기_등급(t+1).csv')
s1_shift.to_csv('csv/재무비율/최종/등급/사회_1기_등급(t+1).csv')
g1_shift.to_csv('csv/재무비율/최종/등급/지배구조_1기_등급(t+1).csv')
t1_shift.to_csv('csv/재무비율/최종/등급/통합등급_1기_등급(t+1).csv')

esg2_shift.to_csv('csv/재무비율/최종/등급/esg2기_등급(t+1).csv')

## t-1 년도 esg 등급 데이터프레임

In [40]:
e1_shift = e1_total.copy()
e1_shift['t-1년도_환경등급'] = e1_total.groupby(['종목명','업종명','종목코드'])['환경_등급'].shift(1)
e1_shift.dropna(inplace=True)
e1_shift.reset_index(drop=True, inplace=True)

s1_shift = s1_total.copy()
s1_shift['t-1년도_사회등급'] = s1_total.groupby(['종목명','업종명','종목코드'])['사회_등급'].shift(1)
s1_shift.dropna(inplace=True)
s1_shift.reset_index(drop=True, inplace=True)

g1_shift = g1_total.copy()
g1_shift['t-1년도_지배구조등급'] = g1_total.groupby(['종목명','업종명','종목코드'])['지배구조_등급'].shift(1)
g1_shift.dropna(inplace=True)
g1_shift.reset_index(drop=True, inplace=True)

t1_shift = t1_total.copy()
t1_shift['t-1년도_통합등급'] = t1_total.groupby(['종목명','업종명','종목코드'])['통합_등급'].shift(1)
t1_shift.dropna(inplace=True)
t1_shift.reset_index(drop=True, inplace=True)

esg2_shift = esg2_total.copy()
esg2_shift[['t-1년도_환경등급','t-1년도_사회등급','t-1년도_지배구조등급','t-1년도_통합등급']] = esg2_total.groupby(['종목명','업종명','종목코드'])[['환경_등급','사회_등급','지배구조_등급','통합_등급']].shift(1)
esg2_shift.dropna(inplace=True)
esg2_shift.reset_index(drop=True, inplace=True)

In [28]:
e1_shift.to_csv('csv/재무비율/최종/등급/환경_1기_등급(t-1).csv')
s1_shift.to_csv('csv/재무비율/최종/등급/사회_1기_등급(t-1).csv')
g1_shift.to_csv('csv/재무비율/최종/등급/지배구조_1기_등급(t-1).csv')
t1_shift.to_csv('csv/재무비율/최종/등급/통합등급_1기_등급(t-1).csv')

esg2_shift.to_csv('csv/재무비율/최종/등급/esg2기_등급(t-1).csv')

## t-1 t-2

In [42]:
e1_shift = e1_total.copy()
e1_shift['t-1년도_환경등급'] = e1_total.groupby(['종목명','업종명','종목코드'])['환경_등급'].shift(1)
e1_shift['t-2년도_환경등급'] = e1_total.groupby(['종목명','업종명','종목코드'])['환경_등급'].shift(2)
e1_shift.dropna(inplace=True)
e1_shift.reset_index(drop=True, inplace=True)

s1_shift = s1_total.copy()
s1_shift['t-1년도_사회등급'] = s1_total.groupby(['종목명','업종명','종목코드'])['사회_등급'].shift(1)
s1_shift['t-2년도_사회등급'] = s1_total.groupby(['종목명','업종명','종목코드'])['사회_등급'].shift(2)
s1_shift.dropna(inplace=True)
s1_shift.reset_index(drop=True, inplace=True)

g1_shift = g1_total.copy()
g1_shift['t-1년도_지배구조등급'] = g1_total.groupby(['종목명','업종명','종목코드'])['지배구조_등급'].shift(1)
g1_shift['t-2년도_지배구조등급'] = g1_total.groupby(['종목명','업종명','종목코드'])['지배구조_등급'].shift(2)
g1_shift.dropna(inplace=True)
g1_shift.reset_index(drop=True, inplace=True)

t1_shift = t1_total.copy()
t1_shift['t-1년도_통합등급'] = t1_total.groupby(['종목명','업종명','종목코드'])['통합_등급'].shift(1)
t1_shift['t-2년도_통합등급'] = t1_total.groupby(['종목명','업종명','종목코드'])['통합_등급'].shift(2)
t1_shift.dropna(inplace=True)
t1_shift.reset_index(drop=True, inplace=True)

esg2_shift = esg2_total.copy()
esg2_shift[['t-1년도_환경등급','t-1년도_사회등급','t-1년도_지배구조등급','t-1년도_통합등급']] = esg2_total.groupby(['종목명','업종명','종목코드'])[['환경_등급','사회_등급','지배구조_등급','통합_등급']].shift(1)
esg2_shift[['t-2년도_환경등급','t-2년도_사회등급','t-2년도_지배구조등급','t-2년도_통합등급']] = esg2_total.groupby(['종목명','업종명','종목코드'])[['환경_등급','사회_등급','지배구조_등급','통합_등급']].shift(2)
esg2_shift.dropna(inplace=True)
esg2_shift.reset_index(drop=True, inplace=True)

In [43]:
e1_shift

,종목명,업종명,종목코드,결산월,회계연도,주기,총자산(천원),유동자산(천원),매출채권(천원),재고자산(천원),...,영업이익(천원)_증가율(%),당기순이익(천원)_증가율(%),영업활동으로인한현금흐름(천원)_증가율(%),투자활동으로인한현금흐름(천원)_증가율(%),총자산(천원)_회전율,총자본(천원)_회전율,총부채(천원)_회전율,환경_등급,t-1년도_환경등급,t-2년도_환경등급
0,AK홀딩스,기타금융,A006840,12,2013,Annual,2.374994e+09,7.025583e+08,300681262,141634818,...,302.509703,-44.002663,1049.631550,-422.996213,0.943569,3.528971,1.287935,2.0,2.0,3.0
1,AK홀딩스,기타금융,A006840,12,2014,Annual,2.773154e+09,8.606906e+08,330216202,229358723,...,35.402624,-12.942332,20.406794,-1115.904708,1.036320,3.475007,1.476704,2.0,2.0,2.0
2,AK홀딩스,기타금융,A006840,12,2015,Annual,2.495515e+09,9.691790e+08,224543905,203315762,...,-27.929648,-139.708844,-35.720894,-174.076296,1.124877,3.113541,1.761158,2.0,2.0,2.0
3,AK홀딩스,기타금융,A006840,12,2016,Annual,2.741947e+09,1.179858e+09,266392319,197859303,...,100.975753,-456.066876,125.354273,-189.659189,1.065605,2.888838,1.688407,3.0,2.0,2.0
4,AK홀딩스,기타금융,A006840,12,2017,Annual,2.944784e+09,1.218482e+09,279391346,217784154,...,24.323318,39.071978,-11.741130,127.466951,1.152021,2.944675,1.892350,3.0,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3043,흥아해운,운수창고업,A003280,12,2014,Annual,6.492400e+08,1.534409e+08,34651440,13193030,...,-3.906495,1.063296,-98.376335,-180.023730,1.270940,4.929099,1.712497,3.0,3.0,3.0
3044,흥아해운,운수창고업,A003280,12,2015,Annual,7.916408e+08,1.362803e+08,32088632,11488626,...,14.408829,-42.676587,7667.595814,-102.318119,1.067549,4.882897,1.366253,3.0,3.0,3.0
3045,흥아해운,운수창고업,A003280,12,2016,Annual,9.585323e+08,1.021038e+08,33831395,17967554,...,-72.247242,-263.287062,-104.097563,2351.907560,0.867729,4.321045,1.085767,2.0,3.0,3.0
3046,흥아해운,운수창고업,A003280,12,2017,Annual,8.734091e+08,1.156750e+08,38640814,19976759,...,-320.484176,260.979542,395.969195,-86.417053,0.957658,6.150983,1.134252,3.0,2.0,3.0
3047,흥아해운,운수창고업,A003280,12,2018,Annual,8.036985e+08,1.083550e+08,40090490,18807927,...,-13.821467,39.599067,390.337868,-4345.093446,0.125446,1.378310,0.138007,2.0,3.0,2.0

In [44]:
e1_shift.to_csv('csv/재무비율/최종/등급/환경_1기_등급(t-1, t-2).csv')
s1_shift.to_csv('csv/재무비율/최종/등급/사회_1기_등급(t-1, t-2).csv')
g1_shift.to_csv('csv/재무비율/최종/등급/지배구조_1기_등급(t-1, t-2).csv')
t1_shift.to_csv('csv/재무비율/최종/등급/통합등급_1기_등급(t-1, t-2).csv')

esg2_shift.to_csv('csv/재무비율/최종/등급/esg2기_등급(t-1, t-2).csv')

In [ ]:
e1_shift['t-2년도_환경등급'] = e1_total.groupby(['종목명','업종명','종목코드'])['환경_등급'].shift(2)
e1_shift.dropna(inplace=True)
e1_shift.reset_index(drop=True, inplace=True)

s1_shift['t-2년도_사회등급'] = s1_total.groupby(['종목명','업종명','종목코드'])['사회_등급'].shift(2)
s1_shift.dropna(inplace=True)
s1_shift.reset_index(drop=True, inplace=True)

g1_shift['t-2년도_지배구조등급'] = g1_total.groupby(['종목명','업종명','종목코드'])['지배구조_등급'].shift(2)
g1_shift.dropna(inplace=True)
g1_shift.reset_index(drop=True, inplace=True)

t1_shift['t-2년도_통합등급'] = t1_total.groupby(['종목명','업종명','종목코드'])['통합_등급'].shift(2)
t1_shift.dropna(inplace=True)
t1_shift.reset_index(drop=True, inplace=True)

esg2_shift[['t-2년도_환경등급','t-2년도_사회등급','t-2년도_지배구조등급','t-2년도_통합등급']] = esg2_total.groupby(['종목명','업종명','종목코드'])[['환경_등급','사회_등급','지배구조_등급','통합_등급']].shift(2)
esg2_shift.dropna(inplace=True)
esg2_shift.reset_index(drop=True, inplace=True)

In [30]:
e1_shift['t-2년도_환경등급'] = e1_total.groupby(['종목명','업종명','종목코드'])['환경_등급'].shift(2)
e1_shift.dropna(inplace=True)
e1_shift.reset_index(drop=True, inplace=True)

In [33]:
e1_shift['t-2년도_환경등급'] = e1_total.groupby(['종목명','업종명','종목코드'])['환경_등급'].shift(2)
e1_shift

,종목명,업종명,종목코드,결산월,회계연도,주기,총자산(천원),유동자산(천원),매출채권(천원),재고자산(천원),...,영업이익(천원)_증가율(%),당기순이익(천원)_증가율(%),영업활동으로인한현금흐름(천원)_증가율(%),투자활동으로인한현금흐름(천원)_증가율(%),총자산(천원)_회전율,총자본(천원)_회전율,총부채(천원)_회전율,환경_등급,t-1년도_환경등급,t-2년도_환경등급
0,AK홀딩스,기타금융,A006840,12,2014,Annual,2.773154e+09,8.606906e+08,330216202,229358723,...,35.402624,-12.942332,20.406794,-1115.904708,1.036320,3.475007,1.476704,2.0,2.0,NaN
1,AK홀딩스,기타금융,A006840,12,2015,Annual,2.495515e+09,9.691790e+08,224543905,203315762,...,-27.929648,-139.708844,-35.720894,-174.076296,1.124877,3.113541,1.761158,2.0,2.0,NaN
2,AK홀딩스,기타금융,A006840,12,2016,Annual,2.741947e+09,1.179858e+09,266392319,197859303,...,100.975753,-456.066876,125.354273,-189.659189,1.065605,2.888838,1.688407,3.0,2.0,3.0
3,AK홀딩스,기타금융,A006840,12,2017,Annual,2.944784e+09,1.218482e+09,279391346,217784154,...,24.323318,39.071978,-11.741130,127.466951,1.152021,2.944675,1.892350,3.0,3.0,2.0
4,AK홀딩스,기타금융,A006840,12,2018,Annual,3.397931e+09,1.306700e+09,268844631,227029929,...,1.534637,11.437313,12.929846,-23.216356,1.092189,2.517938,1.928856,2.0,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2661,흥아해운,운수창고업,A003280,12,2012,Annual,5.335714e+08,1.194547e+08,27326735,12765140,...,-620.287876,-180.922734,-566.465935,-882.051580,1.361580,5.827613,1.776691,3.0,3.0,3.0
2662,흥아해운,운수창고업,A003280,12,2013,Annual,5.710601e+08,1.777580e+08,28756477,14418731,...,-43.435139,11.031152,-0.255439,-8.265543,1.348241,4.956174,1.852062,3.0,3.0,3.0
2663,흥아해운,운수창고업,A003280,12,2014,Annual,6.492400e+08,1.534409e+08,34651440,13193030,...,-3.906495,1.063296,-98.376335,-180.023730,1.270940,4.929099,1.712497,3.0,3.0,2.0
2664,흥아해운,운수창고업,A003280,12,2017,Annual,8.734091e+08,1.156750e+08,38640814,19976759,...,-320.484176,260.979542,395.969195,-86.417053,0.957658,6.150983,1.134252,3.0,2.0,NaN
2665,흥아해운,운수창고업,A003280,12,2018,Annual,8.036985e+08,1.083550e+08,40090490,18807927,...,-13.821467,39.599067,390.337868,-4345.093446,0.125446,1.378310,0.138007,2.0,3.0,NaN