In [390]:
import pandas as pd

In [428]:
list_1 = pd.read_csv('csv/종목리스트/최종_1기_리스트_금융업제외.csv', index_col=0)
list_2 = pd.read_csv('csv/종목리스트/최종_2기_리스트_금융업제외.csv', index_col=0)

In [432]:
full = pd.read_csv('csv/재무제표.csv')
full

,종목코드,종목명,결산월,회계년,주기,총자산(천원),유동자산(천원),재고자산(천원),부채및자본총계(천원),매입채무(천원),...,*매출원가율(%),ROE(당기순이익)(%),총자본회전율(회),총부채회전율(회),총자산회전율(회),영업이익률(%),EBIT(천원),당기순이익률(%),매출총이익률(%),유형자산증가율(전년동기)(%)
0,A095570,AJ네트웍스,12,2010,Annual,"223,331,110","43,546,163","2,885,908","223,331,111","9,855,337",...,71.92,6.66,3.29,0.63,0.53,16.19,"18,088,335",2.02,28.08,20.09
1,A095570,AJ네트웍스,12,2011,Annual,"219,085,099","31,232,670","2,561,888","219,085,099","12,904,573",...,74.26,8.97,3.90,0.71,0.60,12.86,"17,091,619",2.30,25.74,3.70
2,A095570,AJ네트웍스,12,2012,Annual,"446,549,322","55,185,893","6,853,246","446,549,323","10,789,926",...,66.19,8.58,2.96,0.68,0.55,13.57,"24,886,942",2.90,33.81,60.59
3,A095570,AJ네트웍스,12,2013,Annual,"1,250,258,683","115,631,563","25,758,904","1,250,258,683","43,830,061",...,0.00,N/A(IFRS),N/A(IFRS),N/A(IFRS),N/A(IFRS),9.32,"70,537,596",2.39,100.00,N/A(IFRS)
4,A095570,AJ네트웍스,12,2014,Annual,"1,437,917,071","144,585,820","20,832,221","1,437,917,071","33,927,425",...,0.00,11.28,4.06,0.92,0.75,7.61,"76,977,721",2.77,100.00,13.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12190,A003280,흥아해운,12,2020,Annual,"286,775,958","59,094,649","7,553,389","286,775,958","11,344,824",...,91.74,"-2,195.07",38.37,0.25,0.25,-6.52,"-5,797,543",-57.20,8.26,-24.76
12191,A003280,흥아해운,12,2021,Annual,"247,298,683","55,263,611","6,823,665","247,298,683","8,879,328",...,93.06,42.88,2.13,0.36,0.31,-2.29,"-1,874,689",20.11,6.94,-20.91
12192,A003280,흥아해운,12,2022,Annual,"317,059,937","105,041,636","9,225,089","317,059,937","12,961,105",...,74.72,19.99,1.49,1.09,0.63,16.69,"29,679,322",13.39,25.28,16.81
12193,A003280,흥아해운,12,2023,Annual,"325,653,339","101,272,964","9,599,208","325,653,339","16,403,753",...,74.13,22.70,1.08,0.98,0.51,14.90,"24,563,228",21.07,25.87,5.57
12194,A003280,흥아해운,12,2024,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [433]:
full_1 = full.loc[(full['회계년'] >= 2010) & (full['회계년'] <= 2018)]
full_2 = full.loc[(full['회계년'] >= 2019) & (full['회계년'] <= 2023)]

full_1 = pd.merge(list_1, full_1, on='종목명')
full_2 = pd.merge(list_2, full_2, on='종목명')

full_1.reset_index(drop=True, inplace=True)
full_2.reset_index(drop=True, inplace=True)

In [434]:
full.columns

Index(['종목코드', '종목명', '결산월', '회계년', '주기', '총자산(천원)', '유동자산(천원)', '재고자산(천원)',
       '부채및자본총계(천원)', '매입채무(천원)', '단기차입금(천원)', '장기차입금(천원)', '매출액(천원)',
       '연구개발비(천원)', '광고선전비(천원)', '영업이익(천원)', '당기순이익(천원)', '영업활동으로인한현금흐름(천원)',
       '투자활동으로인한현금흐름(천원)', '재무활동으로인한현금흐름(천원)', '매출채권(천원)', '자기자본비율(%)',
       '차입금의존도(%)', '부채비율(%)', '차입금비율(%)', '유보율(%)', '매출액증가율(전년동기)(%)',
       '영업이익증가율(전년동기)(%)', '당기순이익증가율(전년동기)(%)', '총자산증가율(전년동기)(%)', '*매출원가율(%)',
       'ROE(당기순이익)(%)', '총자본회전율(회)', '총부채회전율(회)', '총자산회전율(회)', '영업이익률(%)',
       'EBIT(천원)', '당기순이익률(%)', '매출총이익률(%)', '유형자산증가율(전년동기)(%)'],
      dtype='object')

In [435]:
def increase(df, _col) :
    df[_col] = df[_col].str.replace(',','').astype(float)
    df[f'{_col}증가율(%)'] = df.groupby('종목명')[_col].pct_change() * 100

In [436]:
def convert_num(df, _col) :
    df[_col] = df[_col].str.replace(',','').astype(float)

# 성장성 지표

In [437]:
성장성_1 = full_1[['종목명','회계년','총자산증가율(전년동기)(%)','유형자산증가율(전년동기)(%)','매출액증가율(전년동기)(%)','당기순이익(천원)']]
성장성_2 = full_2[['종목명','회계년','총자산증가율(전년동기)(%)','유형자산증가율(전년동기)(%)','매출액증가율(전년동기)(%)','당기순이익(천원)']]

In [438]:
# 성장성_1 = pd.merge(list_1, 성장성_1, on='종목명')
성장성_1.isna().sum()

종목명                 0
회계년                 0
총자산증가율(전년동기)(%)     1
유형자산증가율(전년동기)(%)    1
매출액증가율(전년동기)(%)     1
당기순이익(천원)           0
dtype: int64

In [439]:
성장성_1

,종목명,회계년,총자산증가율(전년동기)(%),유형자산증가율(전년동기)(%),매출액증가율(전년동기)(%),당기순이익(천원)
0,AK홀딩스,2010,N/A(IFRS),N/A(IFRS),N/A(IFRS),"56,728,651"
1,AK홀딩스,2011,25.87,-2.67,-70.00,"43,867,460"
2,AK홀딩스,2012,33.19,40.75,9.68,"193,423,708"
3,AK홀딩스,2013,123.63,413.35,423.51,"108,312,126"
4,AK홀딩스,2014,16.76,15.43,28.24,"94,294,011"
...,...,...,...,...,...,...
4585,흥아해운,2014,13.69,45.19,7.17,"18,347,156"
4586,흥아해운,2015,21.93,49.36,2.42,"10,517,216"
4587,흥아해운,2016,21.08,38.84,-1.58,"-17,173,253"
4588,흥아해운,2017,-8.88,-16.49,0.56,"-61,991,930"
4589,흥아해운,2018,-7.98,-12.08,-87.95,"-86,540,156"

In [440]:
성장성_1.to_csv('csv/재무비율/성장성_1기.csv')
성장성_2.to_csv('csv/재무비율/성장성_2기.csv')

# 규모 지표

In [441]:
규모_1 = full_1[['종목명','회계년','총자산(천원)','EBIT(천원)','단기차입금(천원)','장기차입금(천원)']]
규모_2 = full_2[['종목명','회계년','총자산(천원)','EBIT(천원)','단기차입금(천원)','장기차입금(천원)']]

In [442]:
규모_1['총차입금(천원)'] = 규모_1['단기차입금(천원)'] + 규모_1['장기차입금(천원)']
규모_2['총차입금(천원)'] = 규모_2['단기차입금(천원)'] + 규모_2['장기차입금(천원)']

규모_1.drop(columns=['단기차입금(천원)','장기차입금(천원)'], inplace=True)
규모_2.drop(columns=['단기차입금(천원)','장기차입금(천원)'], inplace=True)

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/441091239.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  규모_1['총차입금(천원)'] = 규모_1['단기차입금(천원)'] + 규모_1['장기차입금(천원)']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/441091239.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  규모_2['총차입금(천원)'] = 규모_2['단기차입금(천원)'] + 규모_2['장기차입금(천원)']
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/441091239.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  규모_1.drop(columns=['단기차입금(천원)','장기차입금(천원)'], inplace=True)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/441091239.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  규모_2.drop(columns=['단기차입금(천원)','장기차입금(천원)'], inplace=True)

In [443]:
규모_1.to_csv('csv/재무비율/규모_1기.csv')
규모_2.to_csv('csv/재무비율/규모_2기.csv')

# 수익성 지표

In [444]:
수익성_1 = full_1[['종목명','회계년','총자산(천원)','*매출원가율(%)','당기순이익(천원)','영업이익률(%)', '매출총이익률(%)','ROE(당기순이익)(%)', '당기순이익률(%)','매출액(천원)']]
수익성_2 = full_2[['종목명','회계년','총자산(천원)','*매출원가율(%)','당기순이익(천원)','영업이익률(%)', '매출총이익률(%)','ROE(당기순이익)(%)', '당기순이익률(%)','매출액(천원)']]

In [445]:
수익성_1.isna().sum()

종목명              0
회계년              0
총자산(천원)          0
*매출원가율(%)        0
당기순이익(천원)        0
영업이익률(%)         0
매출총이익률(%)        0
ROE(당기순이익)(%)    1
당기순이익률(%)        0
매출액(천원)          0
dtype: int64

In [446]:
convert_num(수익성_1, '총자산(천원)')
convert_num(수익성_1, '당기순이익(천원)')
convert_num(수익성_1, '매출액(천원)')
convert_num(수익성_2, '총자산(천원)')
convert_num(수익성_2, '당기순이익(천원)')
convert_num(수익성_2, '매출액(천원)')

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1279276617.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[_col] = df[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1279276617.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[_col] = df[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1279276617.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[_col] = df[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1279276617.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[_col] = df[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1279276617.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[_col] = df[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1279276617.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[_col] = df[_col].str.replace(',','').astype(float)

In [447]:
수익성_1['총자산순이익률(%)'] = (수익성_1['매출액(천원)'] / 수익성_1['총자산(천원)']) * 100
수익성_2['총자산순이익률(%)'] = (수익성_2['매출액(천원)'] / 수익성_2['총자산(천원)']) * 100

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/3535736694.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  수익성_1['총자산순이익률(%)'] = (수익성_1['매출액(천원)'] / 수익성_1['총자산(천원)']) * 100
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/3535736694.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  수익성_2['총자산순이익률(%)'] = (수익성_2['매출액(천원)'] / 수익성_2['총자산(천원)']) * 100

In [448]:
수익성_1.to_csv('csv/재무비율/수익성_1기.csv')
수익성_2.to_csv('csv/재무비율/수익성_2기.csv')

# 안정성 지표

In [449]:
안정성_1 = full_1[['종목명','회계년','유동자산(천원)','총자산(천원)','부채비율(%)','차입금의존도(%)', '자기자본비율(%)', '재고자산(천원)', '매출채권(천원)', '매입채무(천원)', '단기차입금(천원)']]
안정성_2 = full_2[['종목명','회계년','유동자산(천원)','총자산(천원)','부채비율(%)','차입금의존도(%)', '자기자본비율(%)', '재고자산(천원)', '매출채권(천원)', '매입채무(천원)', '단기차입금(천원)']]

In [450]:
안정성_1.columns

Index(['종목명', '회계년', '유동자산(천원)', '총자산(천원)', '부채비율(%)', '차입금의존도(%)',
       '자기자본비율(%)', '재고자산(천원)', '매출채권(천원)', '매입채무(천원)', '단기차입금(천원)'],
      dtype='object')

In [451]:
list = ['유동자산(천원)', '총자산(천원)','재고자산(천원)', '매출채권(천원)', '매입채무(천원)', '단기차입금(천원)']
for _col in list :
    안정성_1[_col] = 안정성_1[_col].str.replace(',','').astype(float)
    안정성_2[_col] = 안정성_2[_col].str.replace(',','').astype(float)

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/88777073.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  안정성_1[_col] = 안정성_1[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/88777073.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  안정성_2[_col] = 안정성_2[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/88777073.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  안정성_1[_col] = 안정성_1[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/88777073.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  안정성_2[_col] = 안정성_2[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/88777073.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  안정성_1[_col] = 안정성_1[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/88777073.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  안정성_2[_col] = 안정성_2[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/88777073.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  안정성_1[_col] = 안정성_1[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/88777073.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  안정성_2[_col] = 안정성_2[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/88777073.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  안정성_1[_col] = 안정성_1[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/88777073.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  안정성_2[_col] = 안정성_2[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/88777073.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  안정성_1[_col] = 안정성_1[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/88777073.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  안정성_2[_col] = 안정성_2[_col].str.replace(',','').astype(float)

In [452]:
안정성_2

,종목명,회계년,유동자산(천원),총자산(천원),부채비율(%),차입금의존도(%),자기자본비율(%),재고자산(천원),매출채권(천원),매입채무(천원),단기차입금(천원)
0,AK홀딩스,2019,1.327787e+09,4.327965e+09,202.67,39.19,33.04,253714985.0,279222938.0,329542790.0,408763625.0
1,AK홀딩스,2020,1.185255e+09,4.152092e+09,228.84,47.88,30.41,236961655.0,243210194.0,275930960.0,697378057.0
2,AK홀딩스,2021,1.352749e+09,4.548737e+09,278.32,49.15,26.43,375434184.0,287334993.0,353029488.0,794593961.0
3,AK홀딩스,2022,1.578818e+09,4.985366e+09,294.61,46.39,25.34,357702292.0,332397459.0,316428299.0,826452036.0
4,AK홀딩스,2023,1.534099e+09,5.314995e+09,310.66,46.06,24.35,334076109.0,382943462.0,322869324.0,957830610.0
...,...,...,...,...,...,...,...,...,...,...,...
3425,효성화학,2019,4.460584e+08,2.063516e+09,353.81,65.25,22.04,127510171.0,143002647.0,132026694.0,43019656.0
3426,효성화학,2020,4.357490e+08,2.417365e+09,500.81,69.26,16.64,143161586.0,174068573.0,146214408.0,192345960.0
3427,효성화학,2021,7.889854e+08,3.044049e+09,522.12,66.73,16.07,392367988.0,214738481.0,235034250.0,339710695.0
3428,효성화학,2022,8.199244e+08,3.131119e+09,"2,631.81",81.80,3.66,353083000.0,248158000.0,284416299.0,645411272.0
3429,효성화학,2023,6.992139e+08,3.115611e+09,"4,934.63",79.67,1.99,368537392.0,211504170.0,275012000.0,689016908.0

In [453]:
안정성_1[안정성_1.isna().any(axis=1)]['종목명'].unique()

array([], dtype=object)

In [454]:
안정성_2[안정성_2.isna().any(axis=1)]['종목명'].unique()

array([], dtype=object)

In [455]:
# list = [안정성_1, 안정성_2]

# for df in list :

#     df['유동비율(%)'] = (df['유동자산(천원)'] / df['총자산(천원)']) * 100
#     df['재고자산대유동자산비율(%)'] = (df['유동자산(천원)'] / df['재고자산(천원)'])  * 100
#     df['매출채권대매입채무비율(%)'] = (df['매입채무(천원)'] / df['매출채권(천원)'])  * 100

#     # df.drop(columns=['유동자산(천원)','총자산(천원)','재고자산(천원)','매출채권(천원)','매입채무(천원)'], inplace=True)

# 안정성_1

In [456]:
안정성_1.to_csv('csv/재무비율/안정성_1기.csv')
안정성_2.to_csv('csv/재무비율/안정성_2기.csv')

### 활동성 지표

In [457]:
활동성_1 = full_1[['종목명','회계년','총자본회전율(회)','총부채회전율(회)', '총자산회전율(회)']]
활동성_2 = full_2[['종목명','회계년','총자본회전율(회)','총부채회전율(회)', '총자산회전율(회)']]

In [458]:
활동성_1.to_csv('csv/재무비율/활동성_1기.csv')
활동성_2.to_csv('csv/재무비율/활동성_2기.csv')

### 현금흐름 지표

In [459]:
현금흐름_1 = full_1[['종목명','회계년','영업활동으로인한현금흐름(천원)', '투자활동으로인한현금흐름(천원)', '재무활동으로인한현금흐름(천원)','총자산(천원)', '부채및자본총계(천원)']]
현금흐름_2 = full_2[['종목명','회계년','영업활동으로인한현금흐름(천원)', '투자활동으로인한현금흐름(천원)', '재무활동으로인한현금흐름(천원)','총자산(천원)', '부채및자본총계(천원)']]

In [460]:
현금흐름_1.columns

Index(['종목명', '회계년', '영업활동으로인한현금흐름(천원)', '투자활동으로인한현금흐름(천원)',
       '재무활동으로인한현금흐름(천원)', '총자산(천원)', '부채및자본총계(천원)'],
      dtype='object')

In [461]:
list = ['영업활동으로인한현금흐름(천원)', '투자활동으로인한현금흐름(천원)','재무활동으로인한현금흐름(천원)', '총자산(천원)', '부채및자본총계(천원)']
for _col in list :
    현금흐름_1[_col] = 현금흐름_1[_col].str.replace(',','').astype(float)
    현금흐름_2[_col] = 현금흐름_2[_col].str.replace(',','').astype(float)

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1419213652.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  현금흐름_1[_col] = 현금흐름_1[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1419213652.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  현금흐름_2[_col] = 현금흐름_2[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1419213652.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  현금흐름_1[_col] = 현금흐름_1[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1419213652.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  현금흐름_2[_col] = 현금흐름_2[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1419213652.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  현금흐름_1[_col] = 현금흐름_1[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1419213652.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  현금흐름_2[_col] = 현금흐름_2[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1419213652.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  현금흐름_1[_col] = 현금흐름_1[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1419213652.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  현금흐름_2[_col] = 현금흐름_2[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1419213652.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  현금흐름_1[_col] = 현금흐름_1[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/1419213652.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  현금흐름_2[_col] = 현금흐름_2[_col].str.replace(',','').astype(float)

In [462]:
df_list = [현금흐름_1, 현금흐름_2]

for df in df_list : 
    df['영업활동CF/총자산(%)'] = (df['영업활동으로인한현금흐름(천원)'] / df['총자산(천원)']) * 100
    df['투자활동CF/총자산(%)'] = (df['투자활동으로인한현금흐름(천원)'] / df['총자산(천원)']) * 100
    df['재무활동CF/총자산(%)'] = (df['재무활동으로인한현금흐름(천원)'] / df['총자산(천원)']) * 100

    df.drop(columns=list, inplace=True)

현금흐름_1

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/663146099.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['영업활동CF/총자산(%)'] = (df['영업활동으로인한현금흐름(천원)'] / df['총자산(천원)']) * 100
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/663146099.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['투자활동CF/총자산(%)'] = (df['투자활동으로인한현금흐름(천원)'] / df['총자산(천원)']) * 100
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/663146099.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['재무활동CF/총자산(%)'] = (df['재무활동으로인한현금흐름(천원)'] / df['총자산(천원)']) * 100
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/663146099.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=list, inplace=True)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/663146099.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['영업활동CF/총자산(%)'] = (df['영업활동으로인한현금흐름(천원)'] / df['총자산(천원)']) * 100
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/663146099.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['투자활동CF/총자산(%)'] = (df['투자활동으로인한현금흐름(천원)'] / df['총자산(천원)']) * 100
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/663146099.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['재무활동CF/총자산(%)'] = (df['재무활동으로인한현금흐름(천원)'] / df['총자산(천원)']) * 100
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/663146099.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=list, inplace=True)

        종목명   회계년  영업활동CF/총자산(%)  투자활동CF/총자산(%)  재무활동CF/총자산(%)
0     AK홀딩스  2010       3.234376      -3.876040      -0.255618
1     AK홀딩스  2011       5.500227     -20.057209      17.250594
2     AK홀딩스  2012       1.494756      -0.555613       4.059223
3     AK홀딩스  2013       7.684153       0.802484      -6.749949
4     AK홀딩스  2014       7.923839      -6.981974       0.100307
...     ...   ...            ...            ...            ...
4585   흥아해운  2014       0.067248       3.992988      -5.655859
4586   흥아해운  2015       4.283938      -0.075912      -3.728428
4587   흥아해운  2016      -0.144974      -1.537221       1.074076
4588   흥아해운  2017      -0.789103      -0.229150       1.658344
4589   흥아해운  2018      -4.204884      10.571370      -6.877314

[4590 rows x 5 columns]

In [463]:
현금흐름_1.to_csv('csv/재무비율/현금흐름_1.csv')
현금흐름_2.to_csv('csv/재무비율/현금흐름_2.csv')

### 기타 지표

In [464]:
기타_1 = full_1[['종목명','회계년','연구개발비(천원)', '광고선전비(천원)', '매출액(천원)']]
기타_2 = full_2[['종목명','회계년','연구개발비(천원)', '광고선전비(천원)', '매출액(천원)']]

In [465]:
기타_1.columns

Index(['종목명', '회계년', '연구개발비(천원)', '광고선전비(천원)', '매출액(천원)'], dtype='object')

In [466]:
list = ['연구개발비(천원)', '광고선전비(천원)', '매출액(천원)']
for _col in list :
    기타_1[_col] = 기타_1[_col].str.replace(',','').astype(float)
    기타_2[_col] = 기타_2[_col].str.replace(',','').astype(float)

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/538245094.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  기타_1[_col] = 기타_1[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/538245094.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  기타_2[_col] = 기타_2[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/538245094.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  기타_1[_col] = 기타_1[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/538245094.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  기타_2[_col] = 기타_2[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/538245094.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  기타_1[_col] = 기타_1[_col].str.replace(',','').astype(float)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/538245094.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  기타_2[_col] = 기타_2[_col].str.replace(',','').astype(float)

In [467]:
df_list = [기타_1, 기타_2]

for df in df_list : 
    df['연구개발비/매출액(%)'] = (df['연구개발비(천원)'] / df['매출액(천원)']) * 100
    df['광고선전비/매출액(%)'] = (df['광고선전비(천원)'] / df['매출액(천원)']) * 100

    df.drop(columns=list, inplace=True)

기타_1

/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/2992736222.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['연구개발비/매출액(%)'] = (df['연구개발비(천원)'] / df['매출액(천원)']) * 100
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/2992736222.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['광고선전비/매출액(%)'] = (df['광고선전비(천원)'] / df['매출액(천원)']) * 100
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/2992736222.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=list, inplace=True)
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/2992736222.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['연구개발비/매출액(%)'] = (df['연구개발비(천원)'] / df['매출액(천원)']) * 100
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/2992736222.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['광고선전비/매출액(%)'] = (df['광고선전비(천원)'] / df['매출액(천원)']) * 100
/var/folders/lj/ms0l79910fz22cg2hchczhw40000gn/T/ipykernel_38026/2992736222.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=list, inplace=True)

        종목명   회계년  연구개발비/매출액(%)  광고선전비/매출액(%)
0     AK홀딩스  2010      0.544563      0.099467
1     AK홀딩스  2011      1.838333      0.322441
2     AK홀딩스  2012      0.613631      0.169591
3     AK홀딩스  2013      0.294822      0.196352
4     AK홀딩스  2014      0.336875      1.292957
...     ...   ...           ...           ...
4585   흥아해운  2014      0.000000      0.030269
4586   흥아해운  2015      0.000000      0.031448
4587   흥아해운  2016      0.000000      0.031021
4588   흥아해운  2017      0.000000      0.026845
4589   흥아해운  2018      0.000000      0.235971

[4590 rows x 4 columns]

In [468]:
기타_1.to_csv('csv/재무비율/기타_1기.csv')
기타_2.to_csv('csv/재무비율/기타_2기.csv')

## 결측치처리

In [196]:
t = 성장성_1[성장성_1.isna().any(axis=1)]
t.loc[(t['회계년'] != 2010) & (t['회계년'] != 2024)]

,종목명,업종명,회계년,총자산증가율(전년동기)(%),유형자산증가율(전년동기)(%),매출액증가율(전년동기)(%),영업이익증가율(전년동기)(%),유동자산(천원)증가율(%),재고자산(천원)증가율(%)
64,DB금융투자,증권,2011,-11.83,-7.95,-18.86,-78.75,NaN,NaN
65,DB금융투자,증권,2012,51.21,226.37,50.20,753.67,NaN,NaN
66,DB금융투자,증권,2013,-5.12,-3.09,-55.71,적전,NaN,NaN
67,DB금융투자,증권,2014,4.40,-3.49,62.35,흑전,NaN,NaN
68,DB금융투자,증권,2015,2.29,1.84,-0.15,-51.23,NaN,NaN
...,...,...,...,...,...,...,...,...,...
4315,흥국화재,보험,2014,17.12,-2.27,34.27,31.66,NaN,NaN
4316,흥국화재,보험,2015,16.61,3.98,10.05,-60.88,NaN,NaN
4317,흥국화재,보험,2016,13.66,2.97,0.47,-11.44,NaN,NaN
4318,흥국화재,보험,2017,9.18,39.96,-5.21,582.56,NaN,NaN
4319,흥국화재,보험,2018,7.04,-1.74,-3.07,-41.37,NaN,NaN

In [204]:
성장성_1[성장성_1.isna().any(axis=1)]['종목명'].unique()

array(['DB금융투자', 'DB손해보험', 'HS애드', 'KB금융', 'NAVER', 'NH투자증권', 'SK증권',
       '갤럭시아에스엠', '교보증권', '기업은행', '다올투자증권', '대신증권', '동양생명', '롯데손해보험',
       '부국증권', '삼성E&A', '삼성증권', '삼성카드', '삼성화재', '상상인증권', '신영증권', '신한지주',
       '유안타증권', '유엔젤', '유진투자증권', '유화증권', '이스타코', '제일기획', '코리안리', '키움증권',
       '텔코웨어', '하나금융지주', '한국금융지주', '한국앤컴퍼니', '한솔로지스틱스', '한양증권', '한전기술',
       '한화손해보험', '한화투자증권', '현대차증권', '현대해상', '흥국화재'], dtype=object)

In [200]:
현금흐름_1.isna().sum()

종목명                   0
회계년                   0
영업활동으로인한현금흐름(천원)    484
투자활동으로인한현금흐름(천원)    484
재무활동으로인한현금흐름(천원)    484
총자산(천원)             484
부채및자본총계(천원)         484
dtype: int64

In [217]:
현금흐름_1

,종목명,회계년,영업활동으로인한현금흐름(천원),투자활동으로인한현금흐름(천원),재무활동으로인한현금흐름(천원),총자산(천원),부채및자본총계(천원)
0,삼성전자,2011,"22,917,901,000","-21,112,564,000","3,109,729,000","155,800,263,000","155,800,263,000"
1,삼성전자,2012,"37,972,809,000","-31,321,554,000","-1,864,508,000","181,071,570,000","181,071,570,000"
2,삼성전자,2013,"46,707,440,000","-44,747,019,000","-4,137,031,000","214,075,018,000","214,075,018,000"
3,삼성전자,2014,"36,975,389,000","-32,806,408,000","-3,057,109,000","230,422,958,000","230,422,958,000"
4,삼성전자,2015,"40,061,761,000","-27,167,787,000","-6,573,509,000","242,179,521,000","242,179,521,000"
...,...,...,...,...,...,...,...
11371,코아스,2014,"9,685,993","-2,353,153","-1,474,616","101,027,896","101,027,896"
11372,코아스,2015,"10,855,928","-3,959,717","623,839","89,438,043","89,438,043"
11373,코아스,2016,"-453,473","-4,609,719","-833,998","76,929,028","76,929,028"
11374,코아스,2017,"-1,283,359","-6,333,274","699,867","79,069,618","79,069,618"
11375,코아스,2018,"2,855,391","-1,743,548","118,813","78,534,357","78,534,357"

In [218]:
현금흐름_1[현금흐름_1.isna().any(axis=1)]['종목명'].nunique()

87

In [348]:
기타_1[기타_1.isna().any(axis=1)]['종목명'].unique()

array([], dtype=object)

In [251]:
성장성_2[성장성_2.isna().any(axis=1)]['종목명'].unique()

array(['기신정기', '대동전자', '동원금속', '신영증권', '오리엔트바이오', '대덕', '비케이탑스'],
      dtype=object)

In [225]:
안정성_2[안정성_2.isna().any(axis=1)]['종목명'].nunique()

51