In [30]:
import pandas as pd

### 리스트 작업

In [31]:
list_1 = pd.read_csv('csv/종목리스트/최종_1기_리스트_금융업제외.csv', index_col=0)
list_2 = pd.read_csv('csv/종목리스트/최종_2기_리스트_금융업제외.csv', index_col=0)

In [3]:
full = pd.read_csv('csv/재무비율/최최최최종_제무제표.csv')
full

,종목코드,종목명,결산월,회계연도,주기,총자산(천원),유동자산(천원),매출채권(천원),재고자산(천원),유형자산(천원),...,차입금의존도(%),부채비율(%),차입금비율(%),*매출원가율(%),ROE(당기순이익)(%),영업이익률(%),EBIT(천원),매출총이익률(%),Unnamed: 35,Unnamed: 36
0,A005930,삼성전자,12,2010,Annual,1.342887e+11,6.140259e+10,1.915311e+10,1.336452e+10,5.296459e+10,...,8.02,50.30,12.06,66.40,19.89,10.75,16621030000.00,33.60,NaN,NaN
1,A005930,삼성전자,12,2011,Annual,1.558003e+11,7.150206e+10,2.188213e+10,1.571672e+10,6.204395e+10,...,9.40,53.78,14.46,67.97,14.43,9.48,15644291000.00,32.03,NaN,NaN
2,A005930,삼성전자,12,2012,Annual,1.810716e+11,8.726902e+10,2.386124e+10,1.774741e+10,6.848474e+10,...,8.23,49.05,12.26,62.98,21.41,14.44,29049338000.00,37.02,NaN,NaN
3,A005930,삼성전자,12,2013,Annual,2.140750e+11,1.107603e+11,2.498853e+10,1.913487e+10,7.549639e+10,...,5.21,42.70,7.44,60.21,22.45,16.08,36785013000.00,39.79,NaN,NaN
4,A005930,삼성전자,12,2014,Annual,2.304230e+11,1.151460e+11,2.469461e+10,1.731750e+10,8.087295e+10,...,4.89,37.08,6.70,62.21,14.71,12.14,25025071000.00,37.79,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12190,A071950,코아스,12,2020,Annual,7.323602e+07,2.976472e+07,8.710062e+06,1.380810e+07,3.678902e+07,...,29.59,205.31,90.34,73.85,(7.07),(2.14),(2100348.37),26.15,NaN,NaN
12191,A071950,코아스,12,2021,Annual,7.929925e+07,3.392668e+07,1.355118e+07,1.469493e+07,3.746555e+07,...,29.11,316.49,121.24,79.02,(24.48),(4.21),(4666241.26),20.98,NaN,NaN
12192,A071950,코아스,12,2022,Annual,7.624612e+07,3.092721e+07,1.066272e+07,1.585842e+07,3.806779e+07,...,39.18,326.67,167.19,75.90,(9.01),(0.72),(704501.53),24.10,NaN,NaN
12193,A071950,코아스,12,2023,Annual,7.044662e+07,2.734730e+07,8.185177e+06,1.372808e+07,3.525787e+07,...,44.08,549.42,286.29,73.99,(46.60),(4.11),(3034190.05),26.01,NaN,NaN
12194,A071950,코아스,12,2024,Annual,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
full_1 = full.loc[(full['회계연도'] >= 2010) & (full['회계연도'] <= 2018)]
full_2 = full.loc[(full['회계연도'] >= 2019) & (full['회계연도'] <= 2023)]

full_1 = pd.merge(list_1, full_1, on='종목명')
full_2 = pd.merge(list_2, full_2, on='종목명')

full_1.reset_index(drop=True, inplace=True)
full_2.reset_index(drop=True, inplace=True)

In [9]:
full_1.to_csv('csv/재무비율/최종_재무제표_1기.csv', encoding='utf-8-sig')
full_2.to_csv('csv/재무비율/최종_재무제표_2기.csv', encoding='utf-8-sig')

### 한글값 처리 후 (ex)완전잠식, 적전 등)

In [128]:
full_1 = pd.read_csv('csv/재무비율/최최최최종_재무제표_1기.csv', index_col=0)
full_2 = pd.read_csv('csv/재무비율/최최최최종_재무제표_2기.csv', index_col=0)

In [129]:
full_1 = full_1.sort_values(by=['종목명','회계연도']).reset_index(drop=True)
full_2 = full_2.sort_values(by=['종목명','회계연도']).reset_index(drop=True)

In [130]:
full_1.columns

Index(['종목명', '업종명', '종목코드', '결산월', '회계연도', '주기', '총자산(천원)', '유동자산(천원)',
       '매출채권(천원)', '재고자산(천원)', '유형자산(천원)', '부채및자본총계(천원)', '총부채(천원)',
       '유동부채(천원)', '매입채무(천원)', '단기차입금(천원)', '장기차입금(천원)', '총자본(천원)', '매출액(천원)',
       '매출원가(천원)', '영업이익(천원)', '연구개발비(천원)', '광고선전비(천원)', '당기순이익(천원)',
       '영업활동으로인한현금흐름(천원)', '투자활동으로인한현금흐름(천원)', '재무활동으로인한현금흐름(천원)', '자기자본비율(%)',
       '차입금의존도(%)', '부채비율(%)', '차입금비율(%)', '*매출원가율(%)', 'ROE(당기순이익)(%)',
       '영업이익률(%)', 'EBIT(천원)', '매출총이익률(%)'],
      dtype='object')

In [131]:
list = ['총자산(천원)', '유동자산(천원)', '매출채권(천원)', '재고자산(천원)', '유형자산(천원)',
        '부채및자본총계(천원)', '총부채(천원)', '유동부채(천원)', '매입채무(천원)', '총자본(천원)',
        '매출액(천원)', '영업이익(천원)', '당기순이익(천원)',
        '영업활동으로인한현금흐름(천원)', '투자활동으로인한현금흐름(천원)', '재무활동으로인한현금흐름(천원)']

for i in list : 
    full_1[i].apply(lambda x : int(x))
    full_2[i].apply(lambda x : int(x))

In [113]:
list = ['총자산(천원)', '유동자산(천원)', '매출채권(천원)', '재고자산(천원)', '유형자산(천원)',
        '부채및자본총계(천원)', '총부채(천원)', '유동부채(천원)', '매입채무(천원)', '총자본(천원)',
        '매출액(천원)', '영업이익(천원)', '당기순이익(천원)',
        '영업활동으로인한현금흐름(천원)', '투자활동으로인한현금흐름(천원)', '재무활동으로인한현금흐름(천원)']

for i in list :
    full_1[f'{i}_증가율(%)'] = full_1.groupby('종목명')[i].pct_change() * 100
    full_2[f'{i}_증가율(%)'] = full_2.groupby('종목명')[i].pct_change() * 100
full_2

,종목명,업종명,종목코드,결산월,회계연도,주기,총자산(천원),유동자산(천원),매출채권(천원),재고자산(천원),...,총부채(천원)_증가율(%),유동부채(천원)_증가율(%),매입채무(천원)_증가율(%),총자본(천원)_증가율(%),매출액(천원)_증가율(%),영업이익(천원)_증가율(%),당기순이익(천원)_증가율(%),영업활동으로인한현금흐름(천원)_증가율(%),투자활동으로인한현금흐름(천원)_증가율(%),재무활동으로인한현금흐름(천원)_증가율(%)
0,AJ네트웍스,서비스업,A095570,12,2019,Annual,1.803255e+09,501055395.0,104945550,58629572,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AJ네트웍스,서비스업,A095570,12,2020,Annual,1.588170e+09,354686634.0,84967285,33664676,...,-10.697852,-11.036088,20.011923,-17.082153,-12.827004,34.760724,-107.873066,-146.758696,118.067385,-288.385876
2,AJ네트웍스,서비스업,A095570,12,2021,Annual,1.355044e+09,273912905.0,93251537,19735720,...,-23.660748,-25.916395,10.200993,25.868145,12.614347,127.945358,-2413.581023,-163.850273,60.122359,7.113492
3,AJ네트웍스,서비스업,A095570,12,2022,Annual,1.483369e+09,329499102.0,95025112,25024737,...,12.809948,59.555191,28.455799,0.325826,21.559602,58.968030,-88.705366,-261.904006,-115.286532,-139.169491
4,AJ네트웍스,서비스업,A095570,12,2023,Annual,1.622157e+09,303255111.0,110780653,17826547,...,7.397490,-19.413997,-7.895728,15.386834,-16.057924,2.574232,90.054421,-199.001294,348.659683,127.442102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3425,흥아해운,운수창고업,A003280,12,2019,Annual,4.309627e+08,93810124.0,2644414,7715548,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3426,흥아해운,운수창고업,A003280,12,2020,Annual,2.867760e+08,59094649.0,1596076,7553389,...,-21.743523,-24.475943,-34.360162,-185.007728,-12.947450,-53.110598,-0.934827,-67.146901,-60.296173,-51.566229
3427,흥아해운,운수창고업,A003280,12,2021,Annual,2.472987e+08,55263611.0,3993001,6823665,...,-53.887761,-82.547985,-21.732342,-491.646312,-8.111781,-67.664078,-132.306680,-33.412729,-71.698726,-145.889194
3428,흥아해운,운수창고업,A003280,12,2022,Annual,3.170599e+08,105041636.0,8413615,9225089,...,25.905092,146.868602,45.969436,31.440659,117.634226,-1683.159767,44.860023,-1342.082087,-117.177029,-147.961887
3429,흥아해운,운수창고업,A003280,12,2023,Annual,3.256533e+08,101272964.0,10919475,9599208,...,-14.753947,-12.329017,26.561377,26.170163,-7.336405,-17.237907,45.878357,-22.495616,1724.800626,140.967309

In [132]:
rotateList = ['총자산(천원)','총자본(천원)','총부채(천원)']

for i in rotateList :
    full_1[f'{i}_회전율'] = full_1['매출액(천원)'].astype(float) / full_1[i] 
    full_2[f'{i}_회전율'] = full_2['매출액(천원)'].astype(float) / full_2[i] 
full_2['총자산(천원)_회전율']

0       0.554697
1       0.549032
2       0.724661
3       0.804690
4       0.617681
          ...
3425    0.237067
3426    0.310134
3427    0.330468
3428    0.560967
3429    0.506095
Name: 총자산(천원)_회전율, Length: 3430, dtype: float64

In [133]:
full_1.columns

Index(['종목명', '업종명', '종목코드', '결산월', '회계연도', '주기', '총자산(천원)', '유동자산(천원)',
       '매출채권(천원)', '재고자산(천원)', '유형자산(천원)', '부채및자본총계(천원)', '총부채(천원)',
       '유동부채(천원)', '매입채무(천원)', '단기차입금(천원)', '장기차입금(천원)', '총자본(천원)', '매출액(천원)',
       '매출원가(천원)', '영업이익(천원)', '연구개발비(천원)', '광고선전비(천원)', '당기순이익(천원)',
       '영업활동으로인한현금흐름(천원)', '투자활동으로인한현금흐름(천원)', '재무활동으로인한현금흐름(천원)', '자기자본비율(%)',
       '차입금의존도(%)', '부채비율(%)', '차입금비율(%)', '*매출원가율(%)', 'ROE(당기순이익)(%)',
       '영업이익률(%)', 'EBIT(천원)', '매출총이익률(%)', '총자산(천원)_회전율', '총자본(천원)_회전율',
       '총부채(천원)_회전율'],
      dtype='object')

In [141]:
a = full_1[full_1['종목명'] == '대덕']
a[['종목명','회계연도','매출액(천원)']]

Empty DataFrame
Columns: [종목명, 회계연도, 매출액(천원)]
Index: []

In [116]:
t = full_1[full_1['재무활동으로인한현금흐름(천원)'] == 0]
t[['종목명','회계연도','재무활동으로인한현금흐름(천원)','재무활동으로인한현금흐름(천원)_증가율(%)']]

          종목명  회계연도  재무활동으로인한현금흐름(천원)  재무활동으로인한현금흐름(천원)_증가율(%)
709    SNT에너지  2017                 0                   -100.0
826   갤럭시아에스엠  2017                 0                   -100.0
827   갤럭시아에스엠  2018                 0                      NaN
1268     대동전자  2018                 0                   -100.0
1557     동남합성  2010                 0                      NaN
1840     모나리자  2014                 0                   -100.0
1841     모나리자  2015                 0                      NaN
2440     세기상사  2011                 0                   -100.0
2441     세기상사  2012                 0                      NaN
2444     세기상사  2015                 0                   -100.0
2445     세기상사  2016                 0                      NaN
2446     세기상사  2017                 0                      NaN
2447     세기상사  2018                 0                      NaN
2486    세우글로벌  2012                 0                   -100.0
2487    세우글로벌  2013                 0                      NaN
2490    세우글로벌  2016                 0                   -100.0
2679     써니전자  2016                 0                   -100.0
3282     일신석재  2016                 0                   -100.0
3284     일신석재  2018                 0                   -100.0
3449     주연테크  2012                 0                   -100.0
3450     주연테크  2013                 0                      NaN
3451     주연테크  2014                 0                      NaN
3452     주연테크  2015                 0                      NaN
3531     천일고속  2013                 0                   -100.0
3533     천일고속  2015                 0                   -100.0
3881    플레이그램  2012                 0                   -100.0
4017     한국주강  2013                 0                   -100.0
4020     한국주강  2016                 0                   -100.0
4054  한국화장품제조  2014                 0                   -100.0
4238  한올바이오파마  2018                 0                   -100.0
4507     화천기계  2017                 0                   -100.0

In [117]:
full_1.loc[full_1['회계연도'] == 2010]

,종목명,업종명,종목코드,결산월,회계연도,주기,총자산(천원),유동자산(천원),매출채권(천원),재고자산(천원),...,총자본(천원)_증가율(%),매출액(천원)_증가율(%),영업이익(천원)_증가율(%),당기순이익(천원)_증가율(%),영업활동으로인한현금흐름(천원)_증가율(%),투자활동으로인한현금흐름(천원)_증가율(%),재무활동으로인한현금흐름(천원)_증가율(%),총자산(천원)_회전율,총자본(천원)_회전율,총부채(천원)_회전율
0,AK홀딩스,기타금융,A006840,12,2010,Annual,6.335185e+08,3.420920e+08,166423031,101257562,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.053673,4.859323,3.556915
9,BYC,섬유의복,A001460,12,2010,Annual,4.100714e+08,1.530529e+08,21453982,122417732,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.503332,0.729953,1.621249
18,CJ,기타금융,A001040,12,2010,Annual,1.380061e+10,4.452779e+09,1171933385,993188483,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.841666,1.932276,1.491212
27,CJ대한통운,운수창고업,A000120,12,2010,Annual,3.909385e+09,7.372997e+08,411326730,14565984,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.630177,1.116813,1.446236
36,CJ씨푸드,음식료품,A011150,12,2010,Annual,6.076672e+07,2.262478e+07,14724179,7241193,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.828017,3.677644,3.634678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4545,효성ITX,서비스업,A094280,12,2010,Annual,5.856878e+07,2.004080e+07,15459581,3553457,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.875102,9.419451,4.138208
4554,후성,화학,A093370,12,2010,Annual,2.437919e+08,8.098500e+07,42779323,24117600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.789112,1.703181,1.470350
4563,휴니드,전기전자,A005870,12,2010,Annual,1.428151e+08,5.281758e+07,9162576,18259843,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.369357,0.732005,0.745549
4572,휴스틸,철강금속,A005010,12,2010,Annual,4.747817e+08,2.096723e+08,89906605,102158190,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.075461,1.478488,3.945292
4581,흥아해운,운수창고업,A003280,12,2010,Annual,5.480929e+08,1.542154e+08,22918510,10768917,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.107039,4.436152,1.475166

In [118]:
full_1 = full_1.loc[full_1['회계연도'] != 2010]
full_2 = full_2.loc[full_2['회계연도'] != 2019]
full_1

,종목명,업종명,종목코드,결산월,회계연도,주기,총자산(천원),유동자산(천원),매출채권(천원),재고자산(천원),...,총자본(천원)_증가율(%),매출액(천원)_증가율(%),영업이익(천원)_증가율(%),당기순이익(천원)_증가율(%),영업활동으로인한현금흐름(천원)_증가율(%),투자활동으로인한현금흐름(천원)_증가율(%),재무활동으로인한현금흐름(천원)_증가율(%),총자산(천원)_회전율,총자본(천원)_회전율,총부채(천원)_회전율
1,AK홀딩스,기타금융,A006840,12,2011,Annual,7.973953e+08,368464610.0,164957170,100459041,...,31.095649,-70.002310,-73.225758,-22.671420,114.044689,551.323235,-8594.279077,0.489446,1.111925,0.874290
2,AK홀딩스,기타금융,A006840,12,2012,Annual,1.062013e+09,455173056.0,243262270,120241742,...,45.532722,9.681788,31.058911,340.927530,-63.805247,-96.310584,-68.660294,0.403073,0.838010,0.776615
3,AK홀딩스,기타금융,A006840,12,2013,Annual,2.374994e+09,702558263.0,300681262,141634818,...,24.315318,423.508219,302.509703,-44.002663,1049.631550,-422.996213,-471.869398,0.943569,3.528971,1.287935
4,AK홀딩스,기타금융,A006840,12,2014,Annual,2.773154e+09,860690585.0,330216202,229358723,...,30.233802,28.242304,35.402624,-12.942332,20.406794,-1115.904708,-101.735166,1.036320,3.475007,1.476704
5,AK홀딩스,기타금융,A006840,12,2015,Annual,2.495515e+09,969178974.0,224543905,203315762,...,9.018106,-2.321824,-27.929648,-139.708844,-35.720894,-174.076296,-5362.170538,1.124877,3.113541,1.761158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4585,흥아해운,운수창고업,A003280,12,2014,Annual,6.492400e+08,153440914.0,34651440,13193030,...,7.760601,7.171915,-3.906495,1.063296,-98.376335,-180.023730,-327.828169,1.270940,4.929099,1.712497
4586,흥아해운,운수창고업,A003280,12,2015,Annual,7.916408e+08,136280257.0,32088632,11488626,...,3.389326,2.420227,14.408829,-42.676587,7667.595814,-102.318119,-19.619621,1.067549,4.882897,1.366253
4587,흥아해운,운수창고업,A003280,12,2016,Annual,9.585323e+08,102103828.0,33831395,17967554,...,11.215038,-1.581947,-72.247242,-263.287062,-104.097563,2351.907560,-134.880925,0.867729,4.321045,1.085767
4588,흥아해운,운수창고업,A003280,12,2017,Annual,8.734091e+08,115675013.0,38640814,19976759,...,-29.354936,0.562842,-320.484176,260.979542,395.969195,-86.417053,40.685889,0.957658,6.150983,1.134252
4589,흥아해운,운수창고업,A003280,12,2018,Annual,8.036985e+08,108354984.0,40090490,18807927,...,-46.207750,-87.946250,-13.821467,39.599067,390.337868,-4345.093446,-481.609845,0.125446,1.378310,0.138007

In [119]:
full_1.loc[full_1[['종목명','재무활동으로인한현금흐름(천원)_증가율(%)']].isna().any(axis=1)]

,종목명,업종명,종목코드,결산월,회계연도,주기,총자산(천원),유동자산(천원),매출채권(천원),재고자산(천원),...,총자본(천원)_증가율(%),매출액(천원)_증가율(%),영업이익(천원)_증가율(%),당기순이익(천원)_증가율(%),영업활동으로인한현금흐름(천원)_증가율(%),투자활동으로인한현금흐름(천원)_증가율(%),재무활동으로인한현금흐름(천원)_증가율(%),총자산(천원)_회전율,총자본(천원)_회전율,총부채(천원)_회전율
827,갤럭시아에스엠,서비스업,A011420,12,2018,Annual,33253331.0,14251248.0,3474166,0,...,-34.627495,-29.407756,88.607574,171.253656,-61.973515,-154.267824,NaN,0.662498,0.832205,3.248741
1841,모나리자,종이목재,A012690,12,2015,Annual,78701061.0,40056623.0,12853306,7399804,...,8.083816,0.125384,-25.877918,-14.498491,-51.445909,131.948127,NaN,1.587939,1.922271,9.130018
2441,세기상사,유통업,A002420,12,2012,Annual,51562689.0,8926750.0,348551,17014,...,-1.933043,1.242113,-18.121957,-13.723774,-76.927262,-50.506242,NaN,0.118380,0.200922,0.288155
2445,세기상사,유통업,A002420,12,2016,Annual,43903385.0,2722030.0,163275,14155,...,-5.585557,-0.199356,-17.998593,-9.748894,15.150890,71.582255,NaN,0.124506,0.226708,0.276181
2446,세기상사,유통업,A002420,12,2017,Annual,43038864.0,2034860.0,230957,22820,...,-1.792664,2.994595,-49.307735,-108.307878,-37.463356,-136.880543,NaN,0.130810,0.237760,0.290803
2447,세기상사,유통업,A002420,12,2018,Annual,42664004.0,2370830.0,190292,17684,...,-1.408414,-7.946793,4.378579,-464.586736,-61.242106,-170.985835,NaN,0.121473,0.221992,0.268266
2487,세우글로벌,유통업,A013000,12,2013,Annual,33460342.0,23746628.0,3890034,3995814,...,3.360412,17.543303,45.495453,-16.397145,285.575667,-142.007559,NaN,1.219209,1.348636,12.704284
3450,주연테크,전기전자,A044380,12,2013,Annual,32224379.0,30908930.0,2197941,5555398,...,-4.702958,-19.451748,-21.627746,-34.147517,-850.400371,-323.527219,NaN,1.868093,2.288441,10.170184
3451,주연테크,전기전자,A044380,12,2014,Annual,30633860.0,29244130.0,2644910,5280762,...,-4.677122,-28.879035,-12.922002,-14.686362,111.167616,54.619317,NaN,1.397587,1.707420,7.701803
3452,주연테크,전기전자,A044380,12,2015,Annual,28466994.0,27176223.0,1457025,5591058,...,-20.934320,21.484657,215.875542,381.271150,-126.542398,236.684767,NaN,1.827092,2.623455,6.018982

In [127]:
import numpy as np

full_1[full_1.isin([np.nan, np.inf])]

,종목명,업종명,종목코드,결산월,회계연도,주기,총자산(천원),유동자산(천원),매출채권(천원),재고자산(천원),...,총자본(천원)_증가율(%),매출액(천원)_증가율(%),영업이익(천원)_증가율(%),당기순이익(천원)_증가율(%),영업활동으로인한현금흐름(천원)_증가율(%),투자활동으로인한현금흐름(천원)_증가율(%),재무활동으로인한현금흐름(천원)_증가율(%),총자산(천원)_회전율,총자본(천원)_회전율,총부채(천원)_회전율
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4588,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4589,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [120]:
full_1.to_csv('csv/재무비율/진짜끝_재무제표_1기.csv', encoding='utf-8-sig')
full_2.to_csv('csv/재무비율/진짜끝_재무제표_2기.csv', encoding='utf-8-sig')